### ISSUE TITLE
The styles of the Native Grid change when the scrollable property is set to 'none'

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#102]
## I'm submitting a...
* Bug report 

## Current behavior
If the **scrollable** property of the Grid is set to '**null**' the header of the Grid changes its background styles a column width, compared to when the property is not set. 

## Expected behavior
The styles of the Grid should not be changed when the **scrollable** property is defined. 

## Minimal reproduction of the problem with instructions
1. Open [this StackBlitz example](https://stackblitz.com/edit/vkceje-vxo3mt?file=src%2Fmain.vue). 
2. Remove the **:scrollable="'none'"** property definition from the Grid and see how it changes

**Comment by zdravkov** [comment]
fixed in version 2.2.2
