### ISSUE TITLE
Blur event not getting fired on dropdownlist wrapper component

### ISSUE THREAD

**Issue by khizarshaikh** [telerik/kendo-vue#103]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by zdravkov** [comment]
The DropDownList Wrapper component does not have blur event as the jQuery DropDownList does not have such event - https://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#events.
If you need such you can submit such request in Kendo jQuery feedback portal - https://feedback.telerik.com/kendo-jquery-ui
As another suggestion you can try to use our Native Vue DropDownList that has a blur event - https://www.telerik.com/kendo-vue-ui/components/dropdowns/dropdownlist/#toc-events
If you have some case that you are not sure how to achieve with the Native DropDownList please submit a support ticket about it so we could be more helpful with a possible solution or guidelines.
