### ISSUE TITLE
Column Menu property is missing in the Gantt component

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#105]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
The column menu property is not available in the Gantt component while it can be configured in the Kendo UI for jQuery version of the product. Here is a link to the API property - https://docs.telerik.com/kendo-ui/api/javascript/ui/gantt/configuration/columnmenu. 

## Expected behavior
The column menu should be available in the Kendo UI for Vue version of the component.

**Comment by zdravkov** [comment]
The property is available in 2021.2.525 of the component.
