### ISSUE TITLE
Native DropDownList(keyboard navigation) - Arrow UP/Down makes 2 steps instead of 1 when :filterable is set to "true"

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#107]
## I'm submitting a...
* Bug report 

## Current behavior
When the filterable property of the Native DropDownList is set to "true" the keyboard navigation is not working as expected. When the arrow up/down button is pressed in opened DropDownList, the selection in the popup is changed with two steps instead of one.  

## Expected behavior
On press of the up/down arrow key, the selection in the DropDownList's popup should be changed with one step, instead of two

## Minimal reproduction of the problem with instructions
1. Open[ this StackBlitz example](https://stackblitz.com/edit/emmcrf-hgv9ud?file=src/main.vue)
2. Click on it to open the popup window
3. Press the arrow down key. The selection is moved to "Football" while the expected behavior is to move to "Basketball"

**Comment by zdravkov** [comment]
fixed in version 2.2.2 - https://stackblitz.com/edit/emmcrf-jsthwx?file=src/main.vue
