### ISSUE TITLE
The "type" prop of the Grid column is not available in the TypeScript definitions in GridColumnProps.d.ts file

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#110]
## I'm submitting a...
* Bug report 

## Current behavior
The "type" GridColumn prop is not available in the Typescript definitions available in the GridColumnProps.d.ts file.  

## Expected behavior
The **type** prop should be available also in the Typescript context as it is available in [this Knowledge base article](https://www.telerik.com/kendo-vue-ui/components/knowledge-base/grid-date-format/)

**Comment by zdravkov** [comment]
fixed in version 2.2.2
