### ISSUE TITLE
A cell with a value of 0 is displayed as an empty one, when editing the Native Grid

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#115]
## I'm submitting a...
* Bug report 

## Current behavior
If a column has a value of 0 and there is no editor defined for this column, when editing Grids' data, the input in which 0 should be displayed is actually empty.  

![image](https://user-images.githubusercontent.com/41293735/121886100-ade2ce00-cd1d-11eb-8f58-98c4be08b91e.png)
![image](https://user-images.githubusercontent.com/41293735/121886106-b0ddbe80-cd1d-11eb-9859-623d1c5eb75b.png)

## Expected behavior
When editing the Native Grid, the data displayed when a row is not in edit mode should be the same as when the same row is in edit mode. 

## Minimal reproduction of the problem with instructions
1. Open [this StackBlitz example](https://stackblitz.com/edit/ncntcu-r8rw4k?file=src/main.vue)
2. Edit a row whose UnitPrice value is 0
3. See the empty input for the UnitPrice field, when the selected row is in the "edit" mode

**Comment by zdravkov** [comment]
fixed in  version 2.2.4
