### ISSUE TITLE
Add filterOperators property to the Native Grid component

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#117]
## I'm submitting a...
* Suggestion for improvement

## Current behavior
If we want to define the filter operators of the different columns in the Native Grid, we can achieve this only by defining a template as it is demonstrated in [this StackBlitz example](https://stackblitz.com/edit/kdpgft-cgpjpz?file=src%2Fmain.vue) (the first column).

## Expected behavior
A property similar to the [filterOperators available ](https://www.telerik.com/kendo-react-ui/components/grid/api/GridProps/#toc-filteroperators)in the KendoReact suite will be very useful.

**Comment by zdravkov** [comment]
shipped om 2.4.0 - https://stackblitz.com/edit/qtodzg?file=src/main.vue
