### ISSUE TITLE
Add custom listener to the templates

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#12]
We need events that could be triggered from the template and handled form the component as in this scenario - https://stackblitz.com/edit/5dqzid-ktee3g?file=index.js

In our to add such possibility we will add 'change' events that will be able to be triggered with an argument form the template

**Comment by JishadMT** [comment]
Passing $listeners on the grid down to the row/cell templates will give the freedom to define custom event listeners on the grid

**Comment by zdravkov** [comment]
Thank  you, @JishadMT for sharing this idea and for your concern with Kendo Native Vue Grid- we will consider it when researching the issue. If you have other improvement ideas about our new Vue Native Grid we will be glad to hear them too. 

Greetings,
Plamen
