### ISSUE TITLE
Wrapper Toolbar click event throws two times on button click 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#129]
## I'm submitting a...
* Bug report 

## Current behavior
The click event of the Toolbar Wrapper component is triggered two times when a button is clicked. 

## Expected behavior
When a button inside the Toolbar is clicked, the click event should be triggered only once. 

## Reproduction 
1. Open [this StackBlitz example](https://stackblitz.com/edit/ev3wtb-1hudkm?file=src%2Fmain.vue)
2. Click on the "Button" button
3. Check the browser's console

**Comment by zdravkov** [comment]
We have provided a special 'kendoclick' event for vue 3 to avoid this issue - https://stackblitz.com/edit/ev3wtb-kgtxlj?file=src%2Fmain.vue
