### ISSUE TITLE
The focused date of the Calendar cannot be changed programmatically 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#142]
## I'm submitting a...
* Bug report 

## Current behavior
When the **focused-date** property of the Calendar is bound to data property, if you change the value of this property the focused date inside the component is not changing

## Expected behavior
If the value of the **focused-date** property is changed, the new focused date should be applied in the Calendar

## Reproduction 
1. Open [this StackBlitz example](https://stackblitz.com/edit/abh8fa-9h2fph?file=src/main.vue)
2. Change the default focused date to the new one with a click on the "Change focused date" button
3. Nothing changes in the Calendar

**Comment by zdravkov** [comment]
Currently the focused-date prop is 'Sets the initial focused date of the Calendar.' as it is described in our documentation [here](https://www.telerik.com/kendo-vue-ui/components/dateinputs/api/CalendarProps/#toc-focuseddate). If you want to reset it on some occasion you can use the key prop to re-mount the component as it is done here - https://stackblitz.com/edit/abh8fa-uzr89j?file=src/main.vue

**Comment by zdravkov** [comment]
After a deeper investigation we decided to treat this as a bug and  it is fixed in 2.3.1 version - https://stackblitz.com/edit/abh8fa-xssjez?file=src%2Fmain.vue
