### ISSUE TITLE
Scheduler component doesn't support year view

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#143]
The Kendo UI for Vue Scheduler Wrapper doesn't support year view which is available in the jQuery suite. 

**To reproduce the issue follow the below steps:**
1. Open [this StackBlitz example](https://stackblitz.com/edit/hbkbva?file=src/main.vue)
2. From the DropDownList in the upper right corner select "Year" 
3. Check the console. The following error appears in it:
![image](https://user-images.githubusercontent.com/41293735/126334486-50fec360-f35b-4581-942f-4f99447421ad.png)

**Expected behavior**
The "Year" view should be available in the Kendo UI for Vue Scheduler Wrapper

**Comment by zdravkov** [comment]
it is working correctly when using the latest official version of Kendo - for example :
```
   <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.2.616/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.2.616/js/kendo.all.min.js"></script>
```
https://stackblitz.com/edit/hbkbva-gdfoqu-ucqsmz?file=public%2Findex.html
