### ISSUE TITLE
The styles of the Calendar component are broken 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#145]
* Bug report:
The styles of the Calendar component are broken in version 4.40.X of the @progress/kendo-theme-default package. 

**Reproduction:** https://stackblitz.com/edit/xjvzsg?file=public%2Findex.html 

**Workaround:** Use version 4.39.0 instead of 4.40.X as it is demonstrated in this example https://stackblitz.com/edit/ub8sa2-94weky?file=public%2Findex.html

**Comment by zdravkov** [comment]
fixed in 2.4.0 version of Kendo UI for Vue
