### ISSUE TITLE
"Jumping" issues and white space at the bottom of Native Grid with Groupable + Virtualization scenario

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#150]
There is an issue with white space that appears when you scroll a Grid with Groupable and Virtualization configurations switched on. 
**Reproduction:**
1. Go to [this article](https://www.telerik.com/kendo-vue-ui/components/grid/grouping/grouping-virtual/).
2. Scroll the Grid till the end of the scroller
3. See the white space.

**Jumping issue:**
When you scroll the linked above example there is a strange "jumping" of the rows.

**Comment by zdravkov** [comment]
New scenarios from ticket 1536648 - 
Closing a second-level group and then scrolling away from it shows it as expanded when you scroll back.
Scrolling around tends to jump and the scroll behavior is not smooth at all.
Collapsing the top level items leaves a huge empty space at the bottom of the scrollable grid area.

All of these problems can be observed in your own example Virtual Scrolling with Grouping at https://www.telerik.com/kendo-vue-ui/components/grid/grouping/grouping-virtual/. Set the groups to Units In Stock and then Category Name for the second level.

**Comment by PekoPPT** [comment]
Once you scroll to the bottom of the Grid items and start scrolling up there are two issues that are observed:
- [ ] It is "hard" to reach row number 1(or zero)
- [ ] While trying to reach the row from the above point, sometimes the scroll goes to the last rows of the Grid - from the area of the first rows to the latest ones in the Grid.

**Comment by zdravkov** [comment]
We have addressed these issues in the latest 3.0.8 version and updated our demo, too - https://www.telerik.com/kendo-vue-ui/components/grid/grouping/grouping-virtual/
