### ISSUE TITLE
The Native NumericTextBox doesn't have the 'k-state-focused' class when focused 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#152]
The Native NumericTextBox doesn't have the 'k-state-focused' class applied to it, once the component is focused. 

For comparison, the Angular and React versions of the same component get this class applied.

- **React**: https://www.telerik.com/kendo-react-ui/components/inputs/numerictextbox/ 

- **Angular**: https://www.telerik.com/kendo-angular-ui/components/inputs/numerictextbox/

**Comment by zdravkov** [comment]
fixed in version 2.4.4 - https://stackblitz.com/edit/2jechj?file=src/main.vue
