### ISSUE TITLE
[Grid] The Column Menu example's code does not work

### ISSUE THREAD

**Issue by RomainLanz** [telerik/kendo-vue#162]
Hey there! 👋🏻 

[On the page explaining how to use the `Column Menu`](https://www.telerik.com/kendo-vue-ui/components/grid/columns/column-menu), the example works but the code given as example does not.

The issue is that the filter menu never open when clicking "Filter" in the dropdown menu.

I have made a video that shows what I am talking about.

https://user-images.githubusercontent.com/2793951/139414298-7813b832-4134-4f4e-bb9b-673ee2a2efd3.mp4

It also seems that there is an `expandChange` method defined in the component, but it is never used.

**Comment by zdravkov** [comment]
It was a bug indeed and it is fixed in version 2.6.2.

Thank you for reporting it!
The expandChange method is indeed not needed - we will remove it as soon as possible
