### ISSUE TITLE
Update deprecated syntax of  slot-scope with the new v-slot

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#17]
The slot syntax was updated in the latest Vue version so we should update our demos - Here is a reference for this change - https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax.

**Comment by mparvanov** [comment]
- [ ] The Stackblitz link need to be updated as well https://www.telerik.com/kendo-vue-ui/components/grid-native/custom-rendering/custom-cells/#toc-using-named-slots
