### ISSUE TITLE
[Grid] GridColumnMenuCheckboxFilter options should be orderable

### ISSUE THREAD

**Issue by RomainLanz** [telerik/kendo-vue#182]
Hey! 👋🏻 

I believe it is pretty common to have options inside this type of filter alphabetically ordered.
As an example, Excel is doing it by default.

When you start to have a lot of options, like countries in my example, it is hard to find the correct one when they are not ordered.
![](https://user-images.githubusercontent.com/2793951/142641636-516cf5d6-1a6c-4af8-afcc-4a3925b0b4c4.png)

There are multiple ways to order those options. I think passing a `sort` function to the component could let the developer choose how to sort them.

```html
<script>
  function sort(a, b) {
    // ...
  }
</script>

<template>
  <!-- ... -->
    <GridColumnMenuCheckboxFilter :options-sorter="sort" />
  <!-- ... -->
</template>
```

**Comment by RomainLanz** [comment]
Hey there! 👋🏻 

Quite question about that: Is there any documentation to build our own `GridColumnMenuCheckboxFilter`?

I see a big performance hit when using the default one. The data are quite huge (12.5MB) and it takes around 5-6s to render the Grid with those filters. Without them, I have no issue.

**Comment by zdravkov** [comment]
Hey there,

First of all - I am sorry for the late response - our main communication channels are the support tickets, forums and the feedback portal - https://www.telerik.com/support/kendo-ui-for-vue. That is why we strongly recommend them for a faster response :).
 Here we mainly keep the bugs also try to catch up with the items yet some questions may slip between and stay unanswered.
As for the question -  we can add an already sorted and paged data to the GridColumnMenyCheckboxFilter component by passing it to its data-items prop. Here is an example - https://stackblitz.com/edit/ce5xxm?file=src%2FColumnMenu.vue
Here you can find the currently supported API - https://www.telerik.com/kendo-vue-ui/components/grid/api/GridColumnMenuCheckboxFilterProps/
In component itself is not a complicated one and just renders the items that we pass as check list so it does not have inbuilt virtualisation.
Hope this information will be helpful.

Greetings,
Plamen

**Comment by zdravkov** [comment]
Closing this for now if you have further questions or other related issues please let me know. :)
