### ISSUE TITLE
The `steps` property of DateTimePicker is not working 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#187]
**Describe the bug**
The `steps` property is not used/read when set on the DateTimePicker component, even though it says it can on the [docs](https://www.telerik.com/kendo-vue-ui/components/dateinputs/api/DateTimePickerProps/#toc-steps). 

**To Reproduce**
1. Open [this StackBlitz link ](https://stackblitz.com/edit/umrg7s-lkjpft?file=src/main.vue)
2. Open the popup of the TimePicker. The **steps** are applied.
3. Open the popup of the DateTimePicker and select a random date
4. The TimePicker inside the DateTimePicker doesn't apply the definition of the **steps** property.

**Expected behavior**
The steps of the TimePicker, inside the DateTimePicker should be the same as those in the TimePicker component.
**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/144246904-b95aeed4-4592-4b62-87d0-1e300091af12.png)

**Comment by zdravkov** [comment]
fixed in version 2.7.0 - https://stackblitz.com/edit/umrg7s-9woguu?file=src/main.vue
