### ISSUE TITLE
The Native Chart component doesn't update reactively on data change

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#188]
**Describe the bug**
The data inside the Chart is not updating when we change the data it is bound to. 

**To Reproduce**
1. Download this project([_re-render.zip](https://github.com/telerik/kendo-vue/files/7684223/_re-render.zip)) and install the NPM packages(run: npm i)
2. Start the project(run: npm run serve)
3. Click on the "Change dataset" button

**Expected behavior**
With each click of the "Change dataset" button, the "Duration" property of the first element inside the "projects" array is being changed. With this change of "Duration", the Chart should be updated. 

**Workaround of the issue**

Set a new **:key** to the ChartWrapper component:
```
<ChartWrapper v-for="chart in chartSetDefinition"
    :key="uuid()"
    :id="chart.id" (...)
```
Where **uuid()** is a function that generates a random **uuid**.

**Comment by zdravkov** [comment]
fixed in 3.1.2 version of Kendo UI for Vue
