### ISSUE TITLE
DropDownList: Unhandled error when using filtering with value and data-item-key properties

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#189]
**Describe the bug**

When filtering the DropDownList data, if both the **value** and the **data-item-key** properties are defined for the component, an error appears in the browser's console. Once the error appears, the popup of the component cannot be closed.

**To Reproduce**

1. Open [this StackBlitz example](https://stackblitz.com/edit/hhwu1m-uf8ykm?file=src/main.vue)
2. In the DropDownList, search/filter for something that doesn't exist. The point here is to get the 'NO DATA FOUND' template displayed.
3. Once that 'NO DATA FOUND' is displayed then delete the searched text

**Expected behavior**
The DropDownList should continue to work with no issues no matter the combination of properties configured for it.  

**Screenshots**
<img width="368" alt="image" src="https://user-images.githubusercontent.com/41293735/146338644-111d34f9-c2e0-46c8-9ff7-6ab284058593.png">

**Comment by zdravkov** [comment]
fixed in version 3.0.0 - https://stackblitz.com/edit/hhwu1m-bg2f2n?file=public%2Findex.html
