### ISSUE TITLE
The Bar Chart is rendering only one column no matter the number of series passed to it

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#195]
**Describe the bug**
The Bar Chart component renders only one column no matter the number of series passed to it. The Bar Chart renders only the first   **seriesitem** passed to it

**To Reproduce**

1. Open [this Dojo example](https://dojo.telerik.com/iLujuHAg) and run it
 
**Expected behavior**

There should be two columns rendered for each category as in [this StackBlitz example](https://stackblitz.com/edit/cqdndj?file=src/main.vue).

**Comment by zdravkov** [comment]
It seems like the Vue syntax in an HTML environment should be very specific and we need to close the tags with a closing tag instead of using a selfclosing tag:
```
     <seriesitem :type="'column'" :gap="5" :data-items="[1, 2, 3, 5, 4]"**></seriesitem>**
        <seriesitem :type="'column'" :data-items="[2, 3, 4, 6, 9]" **></seriesitem>**
```
Here is an example where it worked at my side - https://dojo.telerik.com/oyOHUjIL
