### ISSUE TITLE
TextArea, NumericTexbox & Chip Rendering issues

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#201]
**Describe the bug**
There are some properties that, when defined, are actually not rendered in the different components.
- TextArea
If we want to define a custom CSS class for the component, the class definition is not appearing in the rendering of the component.  Here is a StackBlitz example - https://stackblitz.com/edit/fcpyj1-o8rjxn?file=src/main.vue
- NumericTextbox
If we want to define a custom CSS class for the component, the class definition is not appearing in the rendering of the component.  Here is a StackBlitz example - https://stackblitz.com/edit/xs65is-8sdpm4?file=src/main.vue

- Switch
When passing "null" to the size property of the component, inside the component there is a clas "k-switch-undefined"
![image](https://user-images.githubusercontent.com/41293735/152185298-47715ea0-9af6-4736-981a-744637ff1d07.png)
The above breaks the functionality of being able to define custom size for the Switch. Here is a StackBlitz example demonstrating the issue - https://stackblitz.com/edit/1dqcnd-jnfvyk?file=src/main.vue

- Switch - the track-rounded style is not applying for the **medium** and **large** properties. - https://stackblitz.com/edit/1dqcnd-rsbbid?file=src/main.vue  ; The same example in Angular - https://stackblitz.com/edit/angular-djeaab?file=app/app.component.ts

**Comment by zdravkov** [comment]
fixed in 3.0.5
