### ISSUE TITLE
DatePicker Custom Input scenario throws JS error when pressing the Tab button

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#202]
**Describe the bug**
When using the DatePicker with custom inputs, if you define a value in a random input and press Tab, a JS error appears. 

**To Reproduce**
1. Open[ this demo](https://stackblitz.com/edit/jkz7wt?file=src/main.vue)
2. Click on the first input inside the DatePicker's DateInput
3. Press Tab

**Expected behavior**
The cursor should move to the next input

**Comment by zdravkov** [comment]
fixed in 3.0.5 version of [Kendo UI for Vue](https://www.telerik.com/kendo-vue-ui) - https://stackblitz.com/edit/jkz7wt-qcvsxa?file=src%2Fmain.vue
