### ISSUE TITLE
The "keyup: event is triggered two times for the Input component

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#203]
**Describe the bug**
The "keyup" event is triggered two times

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/bbdpsx?file=src/main.vue)
2. Click on the Input
3. Press enter and check the browser's console

**Expected behavior**
The event should be triggered once per button press.

## Another issue related to the "keyup" event is in Vue 2 context

**Describe the bug**
The "keyup" event is not triggered when defined in Vue 2. 

**To Reproduce**
1. Open [this CodeSandBox example](https://codesandbox.io/s/dazzling-hopper-js6jt?file=/src/App.vue)
2. Click on the Input
3. Press enter and check the browser's console

**Expected behavior**
There should be output in the browser's console. In Vue 2 the event is not triggered.

**Comment by zdravkov** [comment]
fixed in version 3.0.5 of [Kendo UI for Vue](https://www.telerik.com/kendo-vue-ui) - https://stackblitz.com/edit/bbdpsx-xyioup?file=package.json
