### ISSUE TITLE
Localization and Intl Providers throw error when used with Composition API in Vue 2

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#204]
**Describe the bug**

When the Localization and Intl Providers are used in Vue 2 with Composition API, there is an error in the browser's console that appears initially, before any user interaction. The error is "[Vue warn]: Error in data(): "TypeError: ref is not a function"". After this error appears, no matter what values are passed to both the Localization and Intl components, the are not functioning. 

**To Reproduce**
1. Open t[his CodeSandbox example](https://codesandbox.io/s/gifted-heisenberg-62jw7?file=/src/App.vue:0-3394)
2. Open the browser's console and see the error. 

**Expected behavior**
The Localization and Intl Providers should work correctly in both options and composition API contexts

**Screenshots**
<img width="379" alt="image" src="https://user-images.githubusercontent.com/41293735/152824644-6550f6be-6178-4fa2-8bc5-7d5f92350f8a.png">

**Comment by zdravkov** [comment]
fixed in version 3.0.5 of Kendo UI for Vue - https://codesandbox.io/s/optimistic-bash-2dwgi
