### ISSUE TITLE
Dropdowns virtualization scrolling issue 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#205]
**Describe the bug**
The items inside the popup of the Multiselect are not correctly visualized when scrolling the data. The issue can be easily observed in scenarios where the **page size** and the **total** of records are close numbers. 

The issue is that while scrolling, the Multiselect scrolls but the actual contents of the popup don't move until the scroll bar is more than halfway down. 

**To Reproduce**
1. Open [this project](https://stackblitz.com/edit/khd3ab-13rmsl?file=src/main.vue)
2. Start scrolling the items in the MultiSelect

**Expected behavior**
With the move of the popup scroller down, the data should be scrolled too, no matter if the scroller has reached its middle position or not. 

**Screenshots**
The screenshot is from the linked above example. The items displayed in the popup window should be around "Item 50"
<img width="175" alt="image" src="https://user-images.githubusercontent.com/41293735/152969547-042cabe7-c014-4eea-aade-0d9aaf62b982.png">

**Temporary workaround** - https://stackblitz.com/edit/i1hu9w-lped23?file=src%2Fmain.vue

**Comment by zdravkov** [comment]
also reported in ticket - https://supportheroes.telerik.com/ticket/1580235

**Comment by zdravkov** [comment]
fixed in version 3.9.0 of Kendo UI for Vue - https://stackblitz.com/edit/khd3ab-c68qwa?file=public%2Findex.html
