### ISSUE TITLE
Input - the k-invalid style is always presented when "required=true" is defined

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#207]
**Describe the bug**
When the "required" property of the Input is set to "true", the styling of the component is always in an "invalid" state. The "k-invalid" class is always presented in the rendering of the component no matter if there is or isn't a value inside it.

**To Reproduce**
1. Open [this example](https://stackblitz.com/edit/n7nie3?file=src/main.vue)
The inputs inside it are with "invalid" styling

**Expected behavior**
The styling of the Input should be "invalid" only if the component's validation requirements are not met. 

**Screenshots**
<img width="304" alt="image" src="https://user-images.githubusercontent.com/41293735/153220929-a2368f47-1cda-42f8-a0c1-4e52bfbb52be.png">

**Comment by zdravkov** [comment]
fixed in version 3.0.7 - https://stackblitz.com/edit/n7nie3-bfzvvf?file=src/main.vue
