### ISSUE TITLE
Grid Data cannot be grouped if there is a "null" value in a grouped column

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#213]
**Describe the bug**
If you try to group the data in a Grid by a column that has a value of "null", the browser hangs, and an error appears in the console. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/lywk2r?file=src/main.vue)
2. Group the Grid by "Unit Price" field

**Expected behavior**
The data should be grouped according to the values inside the UnitPrice column. A column with an empty header should appear for the group with a "null" value. 

**Screenshots**
<img width="477" alt="image" src="https://user-images.githubusercontent.com/41293735/154671448-913ba238-e55c-47b8-b0b5-7a6853f8d59b.png">

**Workaround**

Convert the "null" values to empty string with a code like this:
`      this.products.forEach((o) => {
        o.UnitPrice = o.UnitPrice === null ? '' : o.UnitPrice;
      });
`
[Here is a modified example](https://stackblitz.com/edit/vwrjyu?file=src/main.vue) in which the above code is added to the **getData** method.

**Comment by kdikov82** [comment]
I am changing the severity and the priority of the issue, since null values should be allowed within the data items

**Comment by PekoPPT** [comment]
The bug is fixed and the fix will be available with the next official version of Kendo UI for Vue
