### ISSUE TITLE
Input disabled prop not defined. But referenced in component.

### ISSUE THREAD

**Issue by asonnleitner** [telerik/kendo-vue#218]
**Describe the bug**
Hello I went through the code of the vue-inputs, and vue labels. There I noticed
your are referencing the prop `this.$props.disabled` but neither of any of those components actually
have that prop defined.

**To Reproduce**
Just look inside the code:
`editorDisabled: this.$props.disabled`

**Expected behavior**
To work. Also until i strictly define either by passing a string value or `true` to disabled $attrs, I am still able to edit the text field.

**Screenshots**
> Input

![input](https://i.imgur.com/iEGVXow.png)

> Floating label

![floating label](https://i.imgur.com/Yyo6tEz.png)

**Comment by zdravkov** [comment]
Thank you for reporting this issue.

We will do our best to fix it for our next patch release. 
Please excuse us for the late response. If you notice other issues with the components or you need some features or other feedback please log them in our [feedback portal here](https://feedback.telerik.com/kendo-vue-ui) where the items are usually answered much faster.

Greetings,
Plamen

**Comment by zdravkov** [comment]
fixed in 3.1.3 version
