### ISSUE TITLE
The Column Menu (filter) popup layout is broken in version 5 of the Kendo Themes

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#220]
**Describe the bug**
The layout of the column menu popup window, inside the Native Grid, is different when using version 4.x.x and version 5.x.x. of the Kendo Themes. 

* The issue is replicable with all Kendo Themes

**To Reproduce**
1. Open [this example](https://stackblitz.com/edit/a4khkn?file=src/main.vue) 
2. Click on the column menu of the **Name** column 
3. Inside the column menu, click on "filter"

**Expected behavior**
There should be a space between the different elements in the **column menu -> filter** popup

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/157414686-9d6afc82-8aa5-4cd9-a514-ad3099c1ddc2.png)

**Comment by zdravkov** [comment]
Dixed in 3.5.1 version of Kendo UI for Vue - https://stackblitz.com/edit/a4khkn-enxmag?file=package.json
