### ISSUE TITLE
Using slots in the Grid(wrapper) works differently in Vue 2 and Vue 3

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#221]
**Describe the bug**
When using a **slot** to define the columns in the Wrapper Grid, the result in Vue 2 and Vue 3 is different. 
- In Vue 2, if we pass 2 columns to the slot, only these two columns are rendered in the component. 
- In Vue 3, no matter how many columns we pass to the slot, the component renders all columns, based on the data in the datasource

**To Reproduce**
Check the two examples below:
- Vue 2 - https://codesandbox.io/s/jovial-hamilton-k6hfl7?file=/src/App.vue 
- Vue 3 - https://codesandbox.io/s/empty-smoke-cnyz0t?file=/src/App.vue 

The two examples use the same implementation but the number of columns rendered in each Grid is different

**Expected behavior**
The two examples should work the same way as in the Vue 2 application.

**Screenshots**
Vue 2: 
![image](https://user-images.githubusercontent.com/41293735/157866325-0fdd96c2-f641-4b9f-90bd-4442eba62ce1.png)
Vue 3: 
![image](https://user-images.githubusercontent.com/41293735/157866402-9328ea90-e021-404d-bb59-811c45b33f3a.png)

**Comment by zdravkov** [comment]
Multiple root templates are allowed in Vue 3 from version 3.9.3 of Kendo UI for Vue
