### ISSUE TITLE
(Native AutoComplete): Access the id of the selected item when working with datasets of objects

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#223]
**Describe the bug**
Currently, when the AutoComplete is bound to a dataset of objects, once an element is selected, it is hard to get the id of the selected element. 

Once the change event of the AutoComplete is triggered, the **text-field** is easily accessible. To take the ID of the selected element we have to git into the available objects. 

**To Reproduce**
1. Open [this project](https://codesandbox.io/s/small-surf-jbdi2d?file=/src/App.vue)
2. Select an item and check the browser's console

**Expected behavior**
To be able to easily access both the ID and the Text field of the selected item

**Comment by zdravkov** [comment]
added in 3.9.3 version of Kendo UI for Vue - https://codesandbox.io/s/upbeat-hugle-i15x1x
