### ISSUE TITLE
The Native TimePicker throws a console error when used with the 'steps' property

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#228]
**Describe the bug**
The Native TimePicker component throws a console error when a value is passed to its **steps** property.

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/btlslp?file=src/main.vue)
2. Click on the TimePicker to expand its popup
3. Open the browser's console

**Expected behavior**
There shouldn't be any Javascript errors when working with the Timepicker

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/160556580-fc18a772-5d98-4013-8f5c-a8cdf89a8b0a.png)

**Comment by zdravkov** [comment]
fixed in 3.1.3 - https://stackblitz.com/edit/btlslp-pvjhrv?file=src/main.vue
