### ISSUE TITLE
TimePicker issues with the 'min' and 'max' properties 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#229]
**Describe the bug**
There are issues with the selection of the "min" and "max" values of the TimePicker when such are selected for the component. 
- The '**min**' value cannot be the first selection the user makes after the initialization of the component. If the user opens the TimePicker's popup, the **min** value is selected by default. If one clicks on the "Set" button the **min** value should be selected but instead, the value is 12:00 AM. 
If the user selects a value different from the **min**, and then tries to select the **min**, the minimum value is correctly selected.  
- The **max** value is correctly selected but the component treats it as an invalid value. 

**To Reproduce**
1. Open [this StackBlitz example ](https://stackblitz.com/edit/cmbl4a?file=src/main.vue)
2. To test the **min** value issue open the TimePicker and click on the "Set" button
2. To test the **max** value issue, open the TimePicker and select 10:15 PM in the popup

**Expected behavior**
Both the **min** and **max** values defined for the component should be selectable and valid values in all use-case scenarios of the TimePicker.

**Comment by zdravkov** [comment]
fixed in 3.1.3 - https://stackblitz.com/edit/cmbl4a-y2uhru?file=src/main.vue
