### ISSUE TITLE
TimePicker with custom DateInput throws error on Tab press

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#230]
**Describe the bug**
The TimePicker with custom inputs is working correctly until we use the Tab button to switch from one input to another. When the Tab button is pressed, an error appears in the console and breaks the application. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/2ugd2x?file=src%2FcustomDateInput.vue)
2. Focus the first input inside the component
3. Press the Tab button

**Expected behavior**
The focus should be changed to the second input

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/161009143-99385d23-ebc0-4878-bce7-a8d96324bdb6.png)

**Comment by zdravkov** [comment]
fixed in 3.1.3 - https://stackblitz.com/edit/2ugd2x-ksbhgn?file=src%2FcustomDateInput.vue
