### ISSUE TITLE
Native Editor doesn't work correctly in specific Vue 2 scenarios

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#232]
**Describe the bug**
The Native Editor blocks the browser when used in Vue 2. Meanwhile, the same component configuration works correctly in Vue 3.

**To Reproduce**
1. Open [this CodeSandbox](https://codesandbox.io/s/interesting-yonath-hvbeyi)(Vue 2)
2. The project cannot be started or blocks the browser

**Expected behavior**
The example above should be working like in [this project](https://stackblitz.com/edit/r3f5ee-efred2?file=src/main.vue)(Vue 3).

**Comment by zdravkov** [comment]
fixed in 3.1.5 - https://codesandbox.io/s/dank-sunset-tmuom0
