### ISSUE TITLE
The resizing "ghost" element is missing in the Timeline and Month views of the Native Scheduler

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#240]
**Describe the bug**
The "ghost" element that appears when we try to resize an event in the Scheduler is missing in the Timeline and Month views.  The result is that the users don't have a visual representation of what is the new size of the event they are modifying. The resizing itself is working correctly. The issue is only with the visual representation. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/7xbzhl?file=src%2Fmain.vue)
2. From the Views in the upper right corner select "Timeline" or "Month" view
3. Select a random event and try to resize it.

**Expected behavior**
An element that shows the possible new size of the event should appear like it is in the Day view, for example.

**Comment by zdravkov** [comment]
fixed in 3.3.2 - https://stackblitz.com/edit/7xbzhl-x6avdu?file=package.json,src%2Fmain.vue
