### ISSUE TITLE
Resources colors not applied correctly on grouped data in the Native Scheduler

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#241]
**Describe the bug**
In scenarios when we have a color applied to a Scheduler resource, the pre-defined color is not visualized as a background if we use the group prop. This happens when the resource is not available in the array passed to the group property. If the resource that holds a color is available in the **group** array, the colors are correctly displayed. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/bbk3gw-3nivrx?file=src%2Fmain.vue)
2. See the 4 events available in the view

**Expected behavior**
The events assigned to Room 1 should be with blue background and the events assigned to Room 2 should be with red/pink background. This should be valid for all scenarios in the Scheduler - with and without grouping. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/169235569-77921c75-5751-4d57-9a4c-8b172f2d5046.png)

**Comment by zdravkov** [comment]
fixed in version 3.3.2 - https://stackblitz.com/edit/bbk3gw-muyvpc?file=package.json,src%2Fmain.vue
