### ISSUE TITLE
NumericTextbox with 'p1', 'p2', 'pX' input formatting doesn't work on manual input

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#245]
**Describe the bug**
When we have a NumericTextbox with formatting set to "p1", "p3"..."pX"(percentage with X decimal numbers) the component is not working correctly when we try to manually enter a value in it. 

- The issue is replicable when you select the content of the component and delete it, before entering a new value. If there is a value in the NumericTextbox and one just selects it and changes it, the issue is not replicating. 
- The issue is not replicable if you use a formating of "p", without a decimal numbers definition

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/tve2bf-4cseoe?file=src%2Fmain.vue) 
2. Select the value in the NumericTextbox and delete it(The NumericTextbox should be empty)
![image](https://user-images.githubusercontent.com/41293735/170669858-1814f3fc-9348-49c0-8e1f-f1b1f6920c25.png)
3. Try to enter 5.75 

**Expected behavior**
The user should be able to manually enter a value by pressing "5" + "." + "7" + "5"

**Screenshots**
![download](https://user-images.githubusercontent.com/41293735/170670201-0eeba2a1-bbca-4cd8-8675-3f1b7d8fb47f.gif)

**Comment by zdravkov** [comment]
fixed in 3.3.3 version -https://stackblitz.com/edit/tve2bf-duup1c?file=package.json
