### ISSUE TITLE
Add an option for a custom template definition in the GridColumnMenuCheckboxFilter component

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#249]
Currently, the  **GridColumnMenuCheckboxFilter** component doesn't provide an option for passing a custom rendering template for the checkboxes in it. 

Providing a [filterUI ](https://www.telerik.com/kendo-vue-ui/components/grid/api/GridColumnMenuFilterProps/#toc-filterui)prop like the one available in the **GridColumnMenuFilter** component will be a handy feature. 
With the implementation of the requested prop, we can implement scenarios like changing a given text with an icon.

**Comment by zdravkov** [comment]
added in version 3.3.4 - https://stackblitz.com/edit/7e62lh?file=src%2Fmain.js
