### ISSUE TITLE
DropDownList placeholder isn't rendered

### ISSUE THREAD

**Issue by markglattback** [telerik/kendo-vue#254]
**Describe the bug**
The DropDownList `placeholder` prop does not render a placeholder

**To Reproduce**
Open [this StackBlitz example](https://stackblitz.com/edit/qjmhzg?file=src/main.vue)

**Expected behavior**
DropDownList renders the supplied placeholder text.

**Comment by zdravkov** [comment]
Hi @markglattback ,
In general, there is no placeholder concept when it comes to DropDownList/HTML select element. The approach that we recommend in such cases is to use the default Item documented here:
https://www.telerik.com/kendo-vue-ui/components/dropdowns/dropdownlist/default-item/
Greetings,
Plamen

**Comment by markglattback** [comment]
Thanks @zdravkov 

In that case I'd suggest that the prop documentation just needs updating to make it clear that [placeholders](https://www.telerik.com/kendo-vue-ui/components/dropdowns/api/DropDownListProps/#toc-placeholder) have no effect.

**Comment by zdravkov** [comment]
Added an explanation in the docs in case anyone needs such functionality and is wandering - https://www.telerik.com/kendo-vue-ui/components/dropdowns/api/DropDownListProps/#toc-placeholder
