### ISSUE TITLE
TextArea Auto-Resizing isn't triggered after an Appearance size change 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#255]
**Describe the bug**
When using the [Auto-Resizing](https://www.telerik.com/kendo-vue-ui/components/inputs/textarea/sizing/#toc-auto-resizing) in combination with the [Appearance size](https://www.telerik.com/kendo-vue-ui/components/inputs/textarea/appearance/#toc-size) the Auto-Resizing isn't triggered again after the Appearance size has been changed. Because of this, the [Native TextArea](https://www.telerik.com/kendo-vue-ui/components/inputs/textarea/) stays to 'big'. The Auto-Resizing is only triggered again when you change the value of the TextArea.

**To Reproduce**

1. Open [this StackBlitz example](https://stackblitz.com/edit/qr5bgg?file=src%2Fmain.vue)
2. Fill in a value
3. Switch the 'Size' DropDownList value to 'Large'.
4. Switch the 'Size' DropDownlist value to 'small'.
5. Additional white space is visible below the value.
6. When changing the value the Auto-Resizing is triggered again.

**Expected behavior**
The TextArea should be resized automatically when changing its "size" appearance property, without the need to update the value of the component

**Comment by zdravkov** [comment]
fixed in 3.3.6 version of Kendo UI for Vue
