### ISSUE TITLE
The DropDownList wont open by clicking on the field text iOS

### ISSUE THREAD

**Issue by asonnleitner** [telerik/kendo-vue#259]
**Describe the bug**
When the `DropDownList` has selected values, it's not possible to open the 
`DropDownList` when by clicking on the `DropDownList`'s text. Instead I have to 
click the `DropDownList`'s button to open the `DropDownList`.

**To Reproduce**
Open any `DropDownList` from with a prefilled value on iOS. And try to open 
it by clicking on the `DropDownList`'s text.

**Expected behavior**
Expected behavior is the same as on desktop.

**Browser**
- OS: [iOS]
- Browser [Chrome, Safari]

**Additional context**
https://drive.google.com/file/d/1eG7AazPByw3Mwm_Rmg-TVVZtVLhu-qPU

**Comment by zdravkov** [comment]
Thank you for reporting the issue - would you please elaborate if you still observe the issue in this isolated example - https://stackblitz.com/edit/qvmsev?file=src%2Fmain.vue because in the example from the video thee may be some other styles that are breaking the functionality?

**Comment by asonnleitner** [comment]
Yes works as it should, so the issue must be in this example https://www.telerik.com/kendo-vue-ui/components/buttons/button/appearance/

**Comment by zdravkov** [comment]
Thank you for elaborating it! We will mark it as demo bug and try to fix it in our demos as soon as possible.

**Comment by asonnleitner** [comment]
The demo still has the bug.
