### ISSUE TITLE
The slot template doesn't support multiple DOM elements on root level

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#263]
**Describe the bug**
When using a slot template inside the Grid, the content of the template should always have only one DOM element on the root level. If there are multiple elements on the root level, only the first element will be rendered.

In scenarios when we add a comment inside the slot template as a first element, the Grid recognizes it as the first element in the template and nothing will be rendered.

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/zgudsc?file=src%2Fmain.vue)
2. See the **Unit Price** column

**Expected behavior**
The rendering of the slot template shouldn't depend on the number of root elements inside it. The template should be rendered in scenarios with both single and multiple elements in the root. 

**Screenshots**
<img width="511" alt="image" src="https://user-images.githubusercontent.com/41293735/178932663-32a22b73-7458-45e6-9d0b-243baa193c83.png">

**Comment by zdravkov** [comment]
for Vue 3 it is fixed in 3.9.3 - https://stackblitz.com/edit/zgudsc-6u5zpx?file=src%2Fmain.vue
