### ISSUE TITLE
kendo grid vue don't initialize because it has problems with Draggable.js

### ISSUE THREAD

**Issue by JoseCanulEI** [telerik/kendo-vue#264]
I can't initialize Kendo Grid because when installing I get an error

"Cannot read properties of undefined (reading '0') at eval (Draggable.js)"

my version of Vue is 2.6.14 and my version of kendo grid is 3.4.3

**Comment by zdravkov** [comment]
Hi @JoseCanulEI,

I tried to replicate the issue in a sample CodeSandbox, but to no avail - https://codesandbox.io/s/vue2-grid-filtering-forked-spzwgt.
Would you please share a bit more information how to replicate the issue so we could be able to inspect it and be more helpful?

Greetings,
Plamen

**Comment by zdravkov** [comment]
Thank you for sharing this information after further investigation it seems like a bug with the earlier versions of Vue 2.* - we will fix it as soon as possible. If you have an [Telerik account ](https://www.telerik.com/login/kendo-vue-ui) with us you can submit a ticket about this issue so we could provide some [Telerik points](https://www.telerik.com/community/telerik-points) for reporting the issue.

Greetings,
Plamen

**Comment by zdravkov** [comment]
Тhe issue should be fixed 3.4.4 - if you still observe it with it please let me know in this issue.
