### ISSUE TITLE
Kendo editor v2020.2.820 not working with slot template

### ISSUE THREAD

**Issue by SaranyaSubramanian10** [telerik/kendo-vue#266]
**Describe the bug**
When using the slot for kendo editor component, the editor breaks with error `TypeError: this.$slots.default is not a function` and doesn't show up on the UI.

**To Reproduce**

1. Open this [codesandbox link](https://codesandbox.io/s/kendo-editor-not-working-example-zr88jm) for the issue example.
2. Check the error console for detailed stack trace.

**Expected behavior**
Kendo editor should show up on the UI

**Screenshots**

![image](https://user-images.githubusercontent.com/43894220/180952443-ed8fd8e6-09a5-4171-a2d5-11b32ee3a540.png)

**Package version**
 - Vue : 2.7.8
- Kendo-editor-vue-wrapper : 2020.2.820

**Additional comments**

Observations:
- Vue v2.6.11 has Kendo editor v2020.2.820 working as expected
- Vue v2.7.8 has Kendo editor v2020.2.722 working as expected

**Comment by zdravkov** [comment]
Thank you for reporting the issue. 
Indeed the 2.7.* version of Vue lead to some issues in our components yet we were able to fix them in the latest version of Kendo UI for Vue wrappers 2022.2.722. 
This is the usual flow of when we find a bug in the newer version of the suite - we provide fixes in the latest versions of the components and recommend using the as the most appropriate ones for the latest version of Vue.
If you have further questions please let me know.
Greetings,
Plamen
