### ISSUE TITLE
DatePicker issues when pressing the Enter key

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#268]
**Describe the bug**
The DatePicker component behaves unexpectedly when it is part of an HTML form that has a Submit button. The things that happen are as follows:
1. If you focus the DatePicker and press **Enter**, the popup of the component opens
2. If there are two DatePickers inside the HTML form, focusing on the second DatePicker and pressing **Enter**, opens the popup of the first DatePicker 

**To Reproduce**

**Scenario 1:** 
1. Open [this project](https://codesandbox.io/s/nostalgic-yalow-fj5bii)
2. Focus the DatePicker and press Enter 

**Scenario 2:** 
1. Open [this project](https://codesandbox.io/s/vigilant-sky-5tpes7?file=/src/main.vue)
2. Focus on the second DatePicker and press Enter 

**Expected behavior**
When pressing **Enter** inside the HTML form, the form should be submitted and no DatePicker popups should open

**Comment by zdravkov** [comment]
Fixed in version 3.4.5 of Kendo UI for Vue
