### ISSUE TITLE
The Native TabStrip component not working correctly in SSR scenario

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#273]
**Describe the bug**
In a Server-side rendering scenario, the tab navigation of the Native TabStrip is not visible right after its load. The tab navigation is not visible until the page gets rehydrated on the client side.

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/nuxt-starter-playground-aucoto?file=pages%2Findex.vue)
2. Reload the result pane a few times

**Expected behavior**
The tab navigation should be visible right after the page load, not when the page gets rehydrated on the client side

**Comment by zdravkov** [comment]
In the newest version have an updated version of Kendo UI for Vue TabStrip that loads its tabs through its tabs prop collection. It has an improvement in the way we read the tabs navigation and allows us to render the tabs correctly in a SSR scenario - https://stackblitz.com/edit/nuxt-starter-playground-knceka?file=pages%2Findex.vue
This approach will be the new one in the future and soon we will update our demos work with it.
