### ISSUE TITLE
Console warning when the pagechange event of the Native ComboBox and MultiSelect is triggered

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#274]
**Describe the bug**
When the PageChange event of the Native ComboBox or MultiSelect is triggered the following warning appears in the browser's console:
![image](https://user-images.githubusercontent.com/41293735/184352264-7b0a06e9-a5b2-4863-9bfd-4322e7606b2d.png)

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/rjemyp?file=src%2Fmain.vue)
2. Expand the popup of the MultiSelect and start scrolling its items
3. Check the browser's console

**Expected behavior**
There shouldn't be any browser warnings when the pagechange event is triggered

**Comment by zdravkov** [comment]
fixed in 3.5.1 version of Kendo UI for Vue  - https://stackblitz.com/edit/rjemyp-agpza5?file=package.json
