### ISSUE TITLE
Native ComboBox and DropDownList doesn't work correctly in virtualization scenario

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#276]
**Describe the bug**
Both the ComboBox and DropDownList don't work as expected when configured in a virtualization scenario. The issue is related to **skip** value available in the event handler of the "pagechange" event. When you scroll the virtualized list down and then start to scroll in back in the upside direction, the value available in the **event.skip** property is at first being changed to a number that is bigger than the current "skip" value.  

The result is that if you are currently at element 5000 in the popup list, and decide to scroll in the upside direction, the list will display items with an ID bigger than 5000 and the scroll in the upside direction will start from this new position. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/dg6e4e?file=src%2Fmain.vue)
2. Open your browser's console
3. Scroll fast to an item with ID of 2000 +
4. Start scrolling up to item 0
5. See the **skip** values in the console.

**Expected behavior**
When scrolling the items in the ComboBox or DropDownList components, the lists should behave the same way no matter if they are configured in a virtualization or default scrolling mode. When the list is scrolled, its items should move up or down without jumping to records that are not in the same direction as the scrolling. 

**Screenshots**

<img width="296" alt="image" src="https://user-images.githubusercontent.com/41293735/184620144-851cd651-a9de-4270-9262-8d0a7a260389.png">

**Comment by zdravkov** [comment]
Fixed in version 3.9.0 of Kendo UI for Vue
