### ISSUE TITLE
DropDownList with Virtualization - Last page dataItems are not displayed until popup scrolling

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#280]
**Describe the bug**
When the Native DropDownList is configured to work in a data virtualization mode, if the user scrolls to the last data page, then close and reopen the popup of the component, no data is visualized in the popup. If the empty popup is scrolled, then the missing data appears back. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/rnjhys?file=src%2Fmain.vue)
2. Open the DropDownList and scroll its data to the end 
3. Click outside the DropDownList to close its popup
4. Click on the DropDownList to open it 

**Expected behavior**
The same data that is visible before the popup is closed, should be visible inside the DropDownList when it is opened on step 4 above. 

**Screenshots**
**When step 4 is done:**
<img width="241" alt="image" src="https://user-images.githubusercontent.com/41293735/186132156-350996db-9892-474f-ba26-aa6d674073a3.png">

**When the popup is scrolled:**
<img width="230" alt="image" src="https://user-images.githubusercontent.com/41293735/186132399-0aa0c14d-ff4f-43a6-b3f6-878ad377bda5.png">

**Comment by zdravkov** [comment]
fixed in version 3.9.0 of Kendo UI for Vue - https://stackblitz.com/edit/rnjhys-mgwh5o?file=public%2Findex.html
