### ISSUE TITLE
[Grid] There is no way to know if a column is filtered or not

### ISSUE THREAD

**Issue by RomainLanz** [telerik/kendo-vue#281]
Hey there! 👋🏻 

There is currently no way in the `html` to know if a column has a filter defined.

```html
<th aria-sort="none" aria-selected="false" colspan="1" rowspan="1" role="columnheader" class="k-header">
  <!-- ... -->
</th>
```

I would like to see something like we have for the sort: `aria-filter="none"`.
This would allow changing the styling accordingly for a better user experience.

**Comment by zdravkov** [comment]
Hi @RomainLanz , 

We have inspected the issue and it seems like we would rather recommend another approach to achieve it.
becasue there is no official aria-filter attribute and adding such would be inappropriate - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques.
Instead we could use the headerClassName property of the Grid Colum - https://www.telerik.com/kendo-vue-ui/components/grid/api/GridColumnProps/#toc-headerclassname.
Here is an exmaple how we could add it based on the current filter and have the possibility to style the filtered column - https://stackblitz.com/edit/1epf79?file=src%2Fmain.vue

Hope that this approach will help you achieve the desired behavior.

if you have further questions or your scenario is somehow different please let em know.

Greetings,
Plamen

**Comment by RomainLanz** [comment]
This looks perfect too!

Thanks for the reply.
