### ISSUE TITLE
The rowReorder event is missing in the Wrapper Grid

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#294]
**Describe the bug**
The **rowReorder** event is missing in the Wrapper Grid component, while it is available in the Kendo UI for jQuery Grid. Currently, the only way the event can be used is by using a code like the below in the mounted hook of the Vue app:
```
    var grid = this.$refs.grid.kendoWidget();
    grid.bind('rowReorder', function (e) {
      console.log('row', e);
    });
```

**Expected behavior**
The **rowReorder** event should be available for usage as the other events of the Wrapper Grid

**Comment by zdravkov** [comment]
fixed - https://stackblitz.com/edit/5nvfdp
