### ISSUE TITLE
SaveExcel.onExportComplete missing from Excel Export package

### ISSUE THREAD

**Issue by jbowmanqci** [telerik/kendo-vue#295]
**Describe the bug**
Saving a grid with the `SaveExcel` function does not fire the `onExportComplete` event. Looking in the npm package code, it does not seem to have that event referenced except in the typescript definition files. It can be found on the web here https://www.telerik.com/kendo-vue-ui/components/excel-export/api/ExcelExportOptions/#toc-onexportcomplete

**To Reproduce**
1. Add the SaveExcel function, making sure to add the `onExportComplete` event
2. Call said function with a button click or similar
3. Watch the console for confirmation that it has been called

Can be reproduced here: https://2ajgmt.stackblitz.io/

**Expected behavior**
onExportComplete should fire

**Browser**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105

**Comment by jbowmanqci** [comment]
Sounds good, thanks for the update and the info!

**Comment by zdravkov** [comment]
fixed in 3.6.4 - https://stackblitz.com/edit/2ajgmt-qpbxzr?file=src%2Fmain.js
