### ISSUE TITLE
A modal appears when double-clicking on a recurring event inside a non-editable Native Scheduler

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#299]
**Describe the bug**
A modal for selecting the editing mode of a recurring event appears on a double click over a recurring event even if the Native Scheduler is not editable. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/ju1gqy?file=src%2Fmain.vue)
2. Double-click on a random recurring event

**Expected behavior**
No popups should appear when double-clicking on an event when the Scheduler is not editable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/192775178-960edbbb-323c-4669-bba3-c696dce60b4e.png)

**Comment by zdravkov** [comment]
fixed in 3.6.4 - https://stackblitz.com/edit/ju1gqy-epmxaa?file=src%2Fmain.vue
