### ISSUE TITLE
kendo[d]Classes typo in the Base component results in an error when changing model value

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-vue#30]
## I'm submitting a...
* Regression report

## Current behavior
kendo[d]Classes typo in the Base component results in an error when changing model value.

## Expected behavior
No error should be thrown

## Minimal reproduction of the problem with instructions
Could be observed in the following StackBlitz: https://stackblitz.com/edit/q7wsg9?file=index.html. Simply select a value in the DatePicker

Browser:
all

**Comment by veselints** [comment]
PR: https://github.com/telerik/kendo-vue-wrappers/pull/533

**Comment by veselints** [comment]
In order to fix that bug, a new version of the kendo Vue wrappers packages has been released: 2019.2.621

**Comment by kinetiq** [comment]
Thanks for the quick turnaround on this. :)
