### ISSUE TITLE
The rowClick and rowDoubleClick events of the TreeList are not triggered 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#307]
**Describe the bug**
The **rowClick** and **rowDoubleClick** events of the TreeList are not triggered or not triggered correctly. 
- The **rowClick** event doesn't actually trigger the **rowClick** but the pointer **click** event. 
- The **doubleClick** event doesn't trigger at all

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/6fyepa-whe5mc?file=src%2Fmain.vue)
2. Click on a randomly selected row
3. DoubleClick on a randomly selected row

**Expected behavior**
When one of the **rowClick** or **doubleClick** events is triggered, in the event handler

**Comment by zdravkov** [comment]
Fixed in 3.6.4 - https://stackblitz.com/edit/6fyepa-ssftmj?file=package.json,src%2Fmain.vue
