### ISSUE TITLE
Grid renders "No data template" only in the first column

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-vue#31]
## I'm submitting a...
* Bug report

## Current behavior
The native Vue Grid "no records" entry spans only over the width of the first column:
https://stackblitz.com/edit/gtqd9r-2i5ldt?file=index.html

## Expected behavior
The "no records" should span over all columns.

## Minimal reproduction of the problem with instructions
Run the following sample: https://stackblitz.com/edit/gtqd9r-2i5ldt?file=index.html

## Environment

Package versions:
kendo-vue-grid 0.3.4

Browser:
all

**Comment by veselints** [comment]
A workaround would be to remove the `<colgroup>` element from the Grid table:
```js
    mounted() {
        this.items = this.createRandomData(0);

        if (this.items.length === 0) {
          var grid = this.$refs.grid;
          var gridElement = grid.$el
          var table = gridElement.children[1].children[0].children[0].children[0];
          var colgroup = table.children[0]

          table.removeChild(colgroup)
        }
    }
```

Here is a sample on the above: https://stackblitz.com/edit/gtqd9r-cbeh2s?file=index.js

**Comment by zdravkov** [comment]
could not replicate it with the latest version - https://stackblitz.com/edit/y5dwns?file=src/main.vue
