### ISSUE TITLE
Filterinig Paginated results (GRID)

### ISSUE THREAD

**Issue by michaelmano** [telerik/kendo-vue#314]
**Describe the issue**
On the react documentation we have clear examples of filtering being used with paginated results.

https://www.telerik.com/kendo-react-ui/components/knowledge-base/grid-multiple-functionalities/

However on the vue version there is no such thing.
https://www.telerik.com/kendo-vue-ui/components/grid/filtering/

Even under the pagination documenation
https://www.telerik.com/kendo-vue-ui/components/grid/paging/

Every time I filter my results the pagination stays on the same page and the results are now on page 1

**Screenshots**

![image](https://user-images.githubusercontent.com/8263631/194992700-1a60160a-af7b-4da1-9b08-2066de266991.png)
![image](https://user-images.githubusercontent.com/8263631/194992764-6a62a31b-5ee4-4b4f-a8eb-675f466a452e.png)

**Comment by zdravkov** [comment]
Thank you for getting in touch with us.

In such case when you want to combine two ways of processing the data we recommend using the process method of the '@progress/kendo-data-query' package as for example it is shown below:
```
products: function () {
      return process(sampleProducts, {
        take: this.take,
        skip: this.skip,
        filter: this.filter,
      });
    },
```
Here is an example that combines the two features - https://stackblitz.com/edit/yg9ndn?file=src%2Fmain.vue
We will do our best to add special page in our docs for explaining these cases.

Last but not least - please excuse me for the late response. We do have a special support channel and there we do answer  the questions much faster so we recommend using it when having questions - [Dedicated Support](https://www.telerik.com/account/support-tickets?supcId=cjj5ut7e400003a6jaog0hzgq).

Regards,
Plamen
