### ISSUE TITLE
Peer dependency requirements prevent project from compiling after following installation instructions

### ISSUE THREAD

**Issue by danielelkington** [telerik/kendo-vue#32]
## Current behavior
When attempting to use the kendo-vue-grid with minimal dependencies, after following the Webpack installation instructions on the [Telerik website](https://www.telerik.com/kendo-vue-ui/components/grid-native/#toc-initializing-with-webpack) and attempting to run the project, a number of error messages regarding missing dependencies is displayed:
```
These dependencies were not found:

* @progress/kendo-data-query in ./node_modules/@progress/kendo-vue-grid/dist/es/columnMenu/GridColumnMenuFilter.js
* @progress/kendo-vue-animation in ./node_modules/@progress/kendo-vue-grid/dist/es/columnMenu/GridColumnMenuItemContent.js
* @progress/kendo-vue-intl in ./node_modules/@progress/kendo-vue-grid/dist/es/GridNoRecords.js, ./node_modules/@progress/kendo-vue-grid/dist/es/cells/GridEditCell.js and 8
others
* @progress/kendo-vue-popup in ./node_modules/@progress/kendo-vue-grid/dist/es/columnMenu/ColumnMenu.js
* vue-class-component in ./node_modules/@progress/kendo-vue-grid/dist/es/GridToolbar.js, ./node_modules/@progress/kendo-vue-grid/dist/es/Grid.js and 32 others
```

## Expected behavior
Either the grid component should run correctly after installing the two dependencies listed on the website (@progress/kendo-theme-default and @progress/kendo-vue-grid) or the documentation should have the correct installation instructions listing all necessary steps.

## Minimal reproduction of the problem with instructions
1. In a fresh Vue project with no kendo dependencies, follow [the official instructions](https://www.telerik.com/kendo-vue-ui/components/grid-native/#toc-initializing-with-webpack) to install the two listed npm dependencies.
2. Register the Grid component as described on that page.
3. Try to compile and run the solution.
I was unable to reproduce this issue on StackBlitz which seems to force peer dependencies to be installed. However I have reproduced this on [CodeSandbox](https://codesandbox.io/s/kendo-grid-minimal-dependencies-4x1k0).

## What is the motivation or use case for changing the behavior?
It should be easy to get started by following the official instructions.

## Environment

Package versions:
```
@progress/kendo-theme-default@4.0.0
@progress/kendo-vue-grid@0.3.4
vue@2.6.10
```
System:
- Node version: 10.16.0
- npm version: 6.9.0
- Platform:  Windows

**Comment by kihashi** [comment]
I also ran into this issue. Installing the listed dependencies is fairly straightforward, but it's really off-putting to have the docs be wrong from the start.

**Comment by zdravkov** [comment]
We will do our best to update the docs as soon as possible - please excuse us for this inconvenience.

**Comment by Dimitar-Goshev** [comment]
Documentation now mentions the needed dependencies to be installed.
