### ISSUE TITLE
The data-grid-row-index attribute of the Native Grid's rows is always -1

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#328]
**Describe the bug**
The value of the **data-grid-row-index** attribute of the different Native Grid rows is always **-1**, no matter the scenario in which the component is used. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/8nm37t?file=src%2Fmain.vue) 
2. Inspect a random Grid row and see its attributes 

**Expected behavior**
The different rows inside the Grid should have different values for the **data-grid-row-index** attribute.

**Comment by zdravkov** [comment]
Fixed in v3.8.1 version of Kendo UI for Vue - https://stackblitz.com/edit/8nm37t-xawwc1?file=src%2Fmain.vue
