### ISSUE TITLE
Grid memory leak with cell and headerCell functional components

### ISSUE THREAD

**Issue by Juveniel** [telerik/kendo-vue#33]
## I'm submitting a...

* Suggestion for improvement

## Current behavior

When the Native Grid columns has `cell` and `headerCell` customization through [functional components](https://vue-loader.vuejs.org/guide/functional.html), the allocated memory by the Grid is not being disposed when switching between Vue router views.

## Expected behavior

The allocated memory should be correctly disposed when working with functional components.

## Minimal reproduction of the problem with instructions

[_kendo-grid-memory-test.zip](https://github.com/telerik/kendo-vue/files/3395807/_kendo-grid-memory-test.zip)

* Start the app 
* Open Chrome 'Memory' tab in DevTools
* Switch between the two routes from the links above the Grid and observe the memory stack.

## Environment

Package versions: kendo-vue-grid 0.3.4

**Comment by zdravkov** [comment]
Functional components templates are not supported option in Kendo UI for Vue.
