### ISSUE TITLE
The 'Upload' doesn't provide option to filter the selected files when 'auto-upload' is true

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#333]
**Describe the bug**
With the current Upload implementation, the component doesn't provide an option to filter the files that are selected for upload if the **auto-upload** property is set to **true**. 

Currently, the files can be filtered only if the **auto-upload** is set to **false** as in [this StackBlitz example](https://stackblitz.com/edit/2nxt2x-chdtnr?file=src%2Fmain.vue). 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/2nxt2x-1h4kw2?file=src%2Fmain.vue) with **auto-upload** property set to **true**
2. Select multiple files + one that has the letter "g" in its name

**Expected behavior**
The file with the letter "g" should not be uploaded 

* As a possible solution for the issue, we can provide an event that is triggered before the file upload and when the event is triggered, the files will be filtered.

**Comment by zdravkov** [comment]
We have added a validateFile prop to validate files with custom logic from v 3.8.1 - you can fin a demo here - https://www.telerik.com/kendo-vue-ui/components/upload/restrictions/#toc-custom-restrictions
