### ISSUE TITLE
Blank space at the bottom of the Grid when configured with :groupable="{ footer: 'visible' }"

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#334]
**Describe the bug**
There is a blank space at the bottom of the Grid when the user scrolls the data. This blank space appears on a specific configuration where the Native Grid is configured with virtual scrolling and the **groupable** property is set as follows:

```
:groupable="{ footer: 'visible' }"
```

* The issue is replicable in both Vue 2 and Vue 3
* The issue is not replicable if the groupable prop is defined like this:
```
:groupable="true"
```

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/bu2c7a-wynxay?file=src%2Fmain.vue) 
2. Scroll the data items to the bottom of the Grid

**Expected behavior**
There shouldn't be any white/blank spaces at the bottom of the Grid 

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/204492508-26e52b04-047f-42f9-95cc-e63a9a65d027.png)

**Comment by PekoPPT** [comment]
There was an improvement in the discussed behavior that was released with R1 2023 release. Still, after additional reports and discussions, there are more things that need to be fixed. The scenarios that should be covered are:
- How the Grid behaves when scrolling the table with a touchpad?
- Make additional testing, when working in Vue 2 context

**Comment by zdravkov** [comment]
fixed in version 3.8.4 of Kendo UI for Vue
