### ISSUE TITLE
Vitest+@testing-library/vue tests fail when the Grid's resizable property is set to true

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#335]
**Describe the bug**
When the Grid's **resizable** property is set to **true**, the following test fails:

```
import { describe, it, expect } from "vitest";
import App from "../App.vue";
import { render } from "@testing-library/vue";

describe("App.vue", () => {
  it("renders apps", async () => {
    render(App);
  });
});
```

* The issue is not replicable if in Draggable.js file the:
```
import KendoDraggable from '@progress/kendo-draggable';
```
is changed with:
```
import { Draggable as KendoDraggable } from '@progress/kendo-draggable';
```

With this error:
![image](https://user-images.githubusercontent.com/41293735/204743305-bf8827f3-0045-4ccc-9e8b-fc6eee51159f.png)

**To Reproduce**
1. Open [this project](https://github.com/telerik/kendo-vue/files/10120958/Resizable-issue.zip)
2. Run 'npm install'
3. Run 'npm run test:unit'

**Expected behavior**
The test should pass as it used to pass in version 3.5.0, for example.

**Comment by zdravkov** [comment]
fixed in v 3.8.2 of Kendo UI for Vue
