### ISSUE TITLE
Kendo Grid (native) should be supported with Rollup

### ISSUE THREAD

**Issue by Iankodj** [telerik/kendo-vue#34]
Currently, there  are circular references that prevent building and running a Vue app with rollup configuration. 

[my-project.zip](https://github.com/telerik/kendo-vue/files/3466190/my-project.zip)

**Comment by veselints** [comment]
When building the attached app (`npm run build`), the following two issues appear:
* `(!) 'this' has been rewritten to 'undefined'`;
* `(!) Circular dependency:` in the:
  * Grid -> HeaderRow -> Grid;
  * main -> Grid -> HeaderRow -> ColumnMenu -> ColumnMenuContent -> main;
  * Grid -> FilterRow -> Grid;
  * main -> Grid -> FilterRow -> GridFilterCell -> main.
