### ISSUE TITLE
Native Tooltip is not hiding in specific scenario

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#343]
**Describe the bug**
The Native Tooltip is not hiding when the mouse cursor is moved fast from the target element in the direction where the Tooltip is about to appear. 

**To Reproduce**
1. Open [this StackBlitz](https://stackblitz.com/edit/snfkjg-jtjfcs?file=src%2Fmain.vue)
2. Hover the Button and move fast the mouse cursor to right(covering the area of the Tooltip)
3. Repeat step 2 multiple times if the Tooltip hides

**Expected behavior**
The Tooltip should disappear when the mouse cursor is moved away from the target element no matter the direction in which the cursor is moved. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/210741879-7d5b1114-e6f1-4549-a32e-ffdad810473f.png)

**Comment by vveesseelliinnaa** [comment]
Reported again in Ticket ID: 1627130

**Comment by BastienDurel** [comment]
It's much easier to reproduce if your tooltip (partly) covers the area which makes it pop

**Comment by BastienDurel** [comment]
Hello. I tried 4.1.0-dev.202311061329, but even with `:anchor-element="'target'"`, there's sometime duplicates, and whithout it, it's easy to get them :(

![image](https://github.com/telerik/kendo-vue/assets/682171/d168843e-29fc-41da-a509-198b929a70dc)

**Comment by elena-gancheva** [comment]
The fix is available in the latest official version [v4.1.0](https://github.com/telerik/kendo-vue-private/releases/tag/v4.1.0)
