### ISSUE TITLE
Incorrect type information for TreeListDataStateChangeEvent

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#347]
**Describe the bug**
The TreeListDataStateChangeEvent type currently has the following props:
- component, dataState and event

While its props should be:
- component, **data** and event

**Expected behavior**

The types defined in the **TreeListDataStateChangeEvent** should be **component**, **data**, and **event**

**Comment by zdravkov** [comment]
fixed in 3.8.0
