### ISSUE TITLE
Native Grid renders <a> tag in its header even if the column is not sortable

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-vue#35]
## I'm submitting a...

* Regression report

## Current behavior
Native Grid renders `<a>` tag in its header even if the column is not sortable. That would result in a cursor pointer to be displayed when hovering over the header.

This is a regression introduced with the 2019.2.621 release

## Expected behavior
`<a>` tag should not be present when the column is not sortable.

## Minimal reproduction of the problem with instructions
Take a look at the overview's basic usage example here [https://www.telerik.com/kendo-vue-ui/components/grid-native/](https://www.telerik.com/kendo-vue-ui/components/grid-native/)

## Environment

Package versions:
2019.2.621 

Browser:
all

**Comment by veselints** [comment]
Until the fix is provided you could use the following workaround:
```css
.k-grid .k-grid-header .k-header>.k-link {
  cursor: default;
}
```

**Comment by bmikaili** [comment]
I believe this is still happening in the newest version.

**Comment by zdravkov** [comment]
Hey @bmikaili ,

I have just checked the rendering of the Grid on[ our demos ](https://www.telerik.com/kendo-vue-ui-develop/components/grid/paging/)but the header tag is not <a> at my side. Would you please elaborate the issue with some link of a demo or a Stackblitz example so we could inspect it and be more helpful?

Greetings,
Plamen

**Comment by bmikaili** [comment]
<img width="443" alt="CleanShot 2023-01-13 at 10 05 30@2x" src="https://user-images.githubusercontent.com/17531789/212281039-509acd4d-0d42-4925-85c8-11e1929d435d.png">

IN the html u can see that the header has no `k-sorted` yet there's a `k-link` inside, which makes the cursor hover. My issue is that I do not want the cursor to be a pointer on unsortable columns.
