### ISSUE TITLE
The TreeList horizontal scrolling is breaking when there are multiple locked columns

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#350]
**Describe the bug**

When we have more than one locked column in a TreeList and scroll the content of the component horizontally, in scenarios when two locked columns are one by one, the layout of the component is breaking. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/n9z6ks?file=src%2Fmain.vue)
2. Scroll the TreeList horizontally to the left
3. See that only the header of the Position column is not moving, while the data of the column is moving along with the data of the other columns. 

**Expected behavior**
The first two columns(Name and Position) should stay locked and the content of the other columns should be scrolled below them. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/214297822-bff52610-cf4c-4cea-baeb-dbfe59a99c34.png)

**Comment by zdravkov** [comment]
fixed in v3.8.2 of Kendo UI for Vue - https://stackblitz.com/edit/n9z6ks-hkepj9?file=src%2Fmain.vue
