### ISSUE TITLE
The date property of the Scheduler is not reactive

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#355]
**Describe the bug**

The Scheduler's date property is not being updated reactively when the value of the data property passed to it is changed

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/e45mpb?file=src%2Fmain.vue)
2. Select a random value in the Calendar above the Scheduler
3. The value of the **schedulerDate** variable is updated but the date inside the Scheduler is not changing

**Expected behavior**
The Scheduler's date should be updated when when the value of the **schedulerDate** variable is changed

**Comment by zdravkov** [comment]
fixed in 3.8.3 version of Kendo UI for Vue - https://stackblitz.com/edit/e45mpb-bb2gxw?file=src%2Fmain.vue
