### ISSUE TITLE
TreeList in inline add/edit mode throws error when using Firefox

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#359]
**Describe the bug**
The Native TreeList component throws an error when used in inline add/edit mode, in the Firefox browser. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/2txlyk?file=src%2Fmain.vue) in the Firefox browser. 
2. Click the "Edit" button on a random row
3. Try to edit the content of the Input that appears in the Name column

**Expected behavior**
The Input's value should be editable and no errors should be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/217829237-f0615fd2-a276-4247-b328-e4e4f4991b02.png)

**Comment by zdravkov** [comment]
fixed in version 3.9.2 of Kendo UI for Vue - https://stackblitz.com/edit/2txlyk-watz7s?file=src%2Fmain.vue
