### ISSUE TITLE
Native Grid: Grouping by column breaks Grid layout when a cell template is applied

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#36]
## I'm submitting a...

* Bug report 

## Current behavior
When there is a custom cell template applied to a column in the **Grid(Native)**, using the grouping functionality breaks **Grid**'s layout

## Expected behavior
The **Grid**'s layout shouldn't be affected if we apply a custom cell template

## Minimal reproduction of the problem with instructions
1. [Open this StackBlitz project](https://stackblitz.com/edit/us1tha-po5vhc?file=index.js) 
2. See that the values in the **ProductName** column are bolded, but **Grid's** layout is broken
3. Remove the cell template definition on line 54 by removing the **cell** property. 
4. Run the project again and see how if we don't apply a cell template, Grid's layout is being displayed correctly

## Environment

Package versions:
```
2019.2.621
```

Browser:
All

**Comment by zdravkov** [comment]
In such case the same template is also used in the cells that separate groups - that is why in such case we recommend using a more specific template that will handle these cases as in this example - https://stackblitz.com/edit/xv1mzd-wxafzq?file=index.html
