### ISSUE TITLE
The Native Grid footer is being scrolled when defined as a part of a locked column

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#360]
**Describe the bug**

When defining a footer in a locked native Grid column, the footer of the column is moving when the content of the Grid is scrolled horizontally. 

**To Reproduce**
1. Open [this CodeSandbox example](https://codesandbox.io/s/lingering-silence-n0dlw3?file=/src/main.js:30-38)
2. Scroll the content of the Grid to the right

**Expected behavior**
The footer inside the ID column should not move when scrolling the Grid's content

**Screenshots**
![image](https://user-images.githubusercontent.com/41293735/218725199-64f6d2b7-941b-4b20-bd2a-38521bfa392f.png)

**Comment by zdravkov** [comment]
fixed in version 3.8.4 in Kendo UI for Vue - https://codesandbox.io/s/modest-monad-t1763b
