### ISSUE TITLE
Native Grid: "or" logic bug in GridColumnMenuFilter

### ISSUE THREAD

**Issue by TolyaDev** [telerik/kendo-vue#37]
## I'm submitting a...
* Bug report

## Current behavior
When trying to filter grid rows by a single column filter which uses "or" logic, rows are not filtered properly and `Error: Cannot read property 'concat' of undefined` is seen in the console.

## Expected behavior
Rows are filtered properly.

## Minimal reproduction of the problem with instructions
See the following Stackblitz: https://stackblitz.com/edit/vzmfzp?file=index.js

### Steps to reproduce
1. Try to set filter on Name column: contains "cha" OR contains "grandma"
2. Check out the console

In the Stackblitz above I inserted `console.log(event.data.filter);` inside `dataStateChange` function. There you can clearly see that `logic` is undefined for the filter, although it should be set to `or`:
![image](https://user-images.githubusercontent.com/2571870/65244680-64833180-daeb-11e9-826d-d324307843b1.png)

## Environment

Package versions:
See `package.json` in Stackblitz

Browser:
- Chrome (desktop) Version 76.0.3809.100 (Official Build) (64-bit)

System:
- Platform:  Ubuntu 18.04

**Comment by IvanDanchev** [comment]
already logged in kendo-ui-core: https://github.com/telerik/kendo-ui-core/issues/5216
