### ISSUE TITLE
JS error is thrown in Editor when replacing content via View Html tool

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-vue#387]
**Describe the bug**
A JS error is thrown when when whole content is replaced via the View HTML tool

Video: http://somup.com/c0fiix4IuA

**To Reproduce**
1. Open this demo: https://stackblitz.com/edit/ygnkdd?file=src%2Fmain.vue
2. Open the View HTML tool
3. Select all of the current content and replace it with a tag/string
4. Click the update Button

**Actual Result**
A `Cannot read properties of undefined (reading 'replace')` JavaScript error is thrown

**Expected behavior**
The content of the editor is replaced with the passed one.

**Additional context**
The reported behavior is not reproducible neither in KendoReact, nor in Angular.

Ticket ID: 1604055

**Comment by zdravkov** [comment]
fixed in version 3.9.3 of Kendo UI for Vue - https://stackblitz.com/edit/ygnkdd-ztbcak?file=src%2Fmain.vue
