### ISSUE TITLE
In specific scenarios the DropDownlistPageChangeEvent returns NaN for its skip property

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#388]
**Describe the bug**
When using the DropDownList component with both filtering and virtualization in specific scenarios, the list will show no items after a series of actions done with the component.

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/vccuzq-khc2cr?file=src%2Fmain.vue)
2. Open the DropDownList
3. Type 33333 into the filter
4. See the 'No data found' result
5. Quickly remove the last two 3's. Now you're only filtering by 333
6. Quickly scroll down
7. Quickly scroll up
8. See 'No data found' appears and the skip value is NaN in the console

**Expected behavior**
The 'No data found' result shouldn't appear in the above scenario and the value of "skip" should not be NaN.

**Comment by zdravkov** [comment]
Fixed in version 4.3.2 of Kendo UI for Vue - https://stackblitz.com/edit/av3cce-grwj1r?file=src%2Fmain.vue
