### ISSUE TITLE
TypeError: kendo.jQuery(...).kendoDropDownTree is not a function

### ISSUE THREAD

**Issue by vlapenkov** [telerik/kendo-vue#39]
I'm trying to get data from json array to kendo-dropdowntree, fiddle is here: http://plnkr.co/edit/GRuLfHLgdlMV2qP7Xafn?p=preview 
DatePicker is working but i need dropdowntree.
Thanks in advance.

**Comment by veselints** [comment]
@vlapenkov The DropDownTree was not available in version 2017.3.913 of Kendo (the all.min.js and the theme versions of Kendo point to that version). After changing the Kendo version to 2018.3.911 (the one used for the Vue wrappers), the DropDownTree initializes properly:
http://plnkr.co/edit/DURPlas7JXEGz7NDUkUW?p=preview
