### ISSUE TITLE
The disabled DropDownList and Button components are focusable

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#391]
**Describe the bug**
When the **AutoComplete** and **Button** components are disabled, they are still focusable. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/ohkpqh?file=src%2Fmain.vue)
2. Press the Tab key to focus the DropDownList
3. Press the Tab key for a second time to focus the Button

**Expected behavior**
When disabled, both the DropDownList and Button should not be focusable

**Comment by zdravkov** [comment]
fixed in -3.10.0 of Kendo UI for Vue - https://stackblitz.com/edit/ohkpqh-qtydk3?file=src%2Fmain.vue
