### ISSUE TITLE
Editor's text underlining does not use the specified font-colour 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#397]
**Describe the bug**
Highlight some text in the Editor. Set a font color other than black, then use the Underline tool.
Once underlined, the text decoration is not the same color as the text.

**To Reproduce**
1. Open https://codesandbox.io/s/great-rosalind-43wdd0
2. Highlight any text
3. Change the font color to anything other than black
4. Use the underline tool to underline the highlighted text
5. Deselect the text and the text decoration and font color do not match.

**Expected behavior**
The font color and underline color should match.

**Comment by PekoPPT** [comment]
The issue is related to this one: https://github.com/telerik/kendo-editor-common/issues/300

**Comment by zdravkov** [comment]
fixed in version 3.11.0
