### ISSUE TITLE
Selecting the text inside an Input that is displayed in a Drawer throws error

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#400]
**Describe the bug**
When we have an Input component that is used inside a Drawer, once the Input's text is selected, a JS error is thrown. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/ttbdt5?file=src%2FSearchView.vue)
2. Click the "Magnifier" icon 
3. Enter random text inside the Input
4. Select the text inside the Input

**Expected behavior**
The selection of the text inside the Input should not trigger any errors

**Comment by PekoPPT** [comment]
There are two possible workarounds that can be used for this bug:
- In main.vue file, define the onSelect method as follows:
-

**Comment by zdravkov** [comment]
fixed in version 3.11.0 of Kendo UI for Vue - https://stackblitz.com/edit/ttbdt5-jfflng?file=src%2FSearchView.vue
