### ISSUE TITLE
The usage of the MultiSelect's listNoDataRender property throws a warning

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#403]
**Describe the bug**
When using the [listNoDataRender](https://www.telerik.com/kendo-vue-ui/components/dropdowns/api/MultiSelectProps/#toc-listnodatarender/) prop of the Native MultiSelect component the following warning appears in the browser's console.
![image](https://github.com/telerik/kendo-vue/assets/41293735/6299b8d2-8adb-460c-96ad-1c9b9db8a2ee)

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/qwmese?file=src%2Fmain.vue)
2. Open the browser's console

**Expected behavior**
No warnings or errors should appear in the dev console

**Comment by zdravkov** [comment]
fixed in 3.10.1 version  of Kendo Ui for Vue - https://stackblitz.com/edit/ttbdt5-dtzpfs?file=src%2FSearchView.vue

**Comment by PekoPPT** [comment]
A new fix for the issue will be available in version 4.1.1 which should be released by the end of the year.
