### ISSUE TITLE
Grid's PDFExport with component doesn't work in Vue 2

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#405]
**Describe the bug**
When using the **GridPdfExport** component for exporting Grid data to a PDF file the exporting operation fails with the following error:
<img width="718" alt="image" src="https://github.com/telerik/kendo-vue/assets/41293735/c531e1c5-5474-45d7-a3ce-4fc9345ce15f">
* The issue is replicable only when working in Vue 2 context

**To Reproduce**
1. Open [this CodeSandbox example](https://codesandbox.io/s/focused-shape-zw4kbo?file=/src/App.vue:569-582)
2. Click the button above the grid

**Expected behavior**
A system dialog should appear asking where the generated file should be saved

**Comment by PekoPPT** [comment]
Discussed in ticket 1610571

**Comment by zdravkov** [comment]
fixed in version 3.11.0 of Kendo UI for Vue - https://codesandbox.io/s/competent-sound-smkuml
