### ISSUE TITLE
The 'modal' property of the Native Window component is not working 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#406]
**Describe the bug**
The [modal property](https://www.telerik.com/kendo-vue-ui/components/dialogs/api/WindowProps/#toc-modal) of the Window is supposed to control if there is a layer behind the component that prevents or allows interaction with the elements that are below the Window.

Currently, there is no way to click the elements behind the Window. 

* Possible workaround is [demonstrated here](https://stackblitz.com/edit/k8uz2e?file=src%2Fmain.vue).  The workaround uses the following CSS:
```
.k-dialog-wrapper {
  height: initial;
  width: initial;
}
```

**To Reproduce**
1. Open [this demo](https://stackblitz.com/edit/ctsnry?file=src%2Fmain.vue)
2. Try to click on the "Close Window" button 

**Expected behavior**
If the modal property is set to false, the user should be able to interact with the HTML elements behind the Window.

**Comment by zdravkov** [comment]
Fixed in version 3.11.0 of Kendo UI for Vue - https://stackblitz.com/edit/ctsnry-qmjf9a?file=src%2Fmain.vue
