### ISSUE TITLE
Issue with kendo-diagram-vue-wrapper type file

### ISSUE THREAD

**Issue by aaf-ww** [telerik/kendo-vue#41]
## I'm submitting a...
* Bug report 

## Current behavior
After installing kendo-diagram-vue-wrapper and kendo-all-vue-wrapper, I get an error about the first package exporting some of the Barcode components which are already being exported by the appropriate package.

## Expected behavior
No errors.

## Minimal reproduction of the problem with instructions
Install the aforementioned packages. When you import something out of the kendo-all-vue-wrapper package, you should get an error about several of the Barcode components being re-exported.

## What is the motivation or use case for changing the behavior?
So that I don't have to manually edit a type file.

## Environment

Package versions:

```
2019.3.1023
```

Browser:

- Chrome (desktop) version XX

System:
- TypeScript version: 3.6.4
- Node version: 10.13
- Platform:  Windows

**Comment by zdravkov** [comment]
Hi @aaf-ww ,

'kendo-all-vue-wrapper' package is rather recommend in cases when CDN version of the components is used and we want to have the code for all the components. In NPM cases we would rather recommend using either the individual 'kendo-diagram-vue-wrapper' or the 'all' package and avoid using them together together.

Greetings,
Plamen

**Comment by aaf-ww** [comment]
Hi @zdravkov,

I appreciate the quick response. I would  like to note that using only kendo-all-vue-wrapper in package.json yields an error like this when attempting to import a specific installer:

"Module '"../../../../../../Users/w26719/Desktop/source/siop-vue/node_modules/@progress/kendo-all-vue-wrapper/types"' has no exported member 'DateinputsInstaller'.ts(2305)"

The error is not satisfied until the corresponding package (in this case, kendo-dateinputs-vue-wrapper) is installed. Thus it seems I am unable to only use the 'all' package as additional packages must still be installed.
