### ISSUE TITLE
The styles defined for the slotTemplate of the Scheduler are not applied in the component

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#412]
**Describe the bug**
With version 3.11.00 of the Native Scheduler, we no longer have to define custom styles for the slots inside the component. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/xqu6vf?file=src%2Fmain.vue)
2. See the Scheduler's slots. Its colors are the default ones

**Expected behavior**
The result should be like in [this StackBlitz example](https://stackblitz.com/edit/nmbctt?file=src%2Fmain.vue,package.json). 

**Screenshots**
Expected result:
![image](https://github.com/telerik/kendo-vue/assets/41293735/ad64ab8d-935c-4e0c-a058-e6e71dafe4c2)

**Comment by zdravkov** [comment]
Fixed in version 3.11.1 of Kendo UI for Vue - https://stackblitz.com/edit/xqu6vf-8pcc4x?file=src%2Fmain.vue
