### ISSUE TITLE
The wrapperStyle prop of the Native TreeList is a required filed in the Typescript definitions

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#415]
**Describe the bug**
When using the TreeList in Typescript the **wrapperStyle** prop should have a definition if you want to use the component. The field is required, and this should be updated. 

**Expected behavior**
The **wrapperStyle** property should not be a required one

**Comment by zdravkov** [comment]
Fixed in version 3.11.1 of Kendo UI for Vue
