### ISSUE TITLE
Grid filtering is equal to does not filter correctly dates

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#42]
## I'm submitting a...

* Bug report 

## Current behavior
Go to
https://www.telerik.com/kendo-vue-ui/components/grid-native/filtering/
clear the filter and try to  filter the date to is equal to  8/12/1996 
No item in the Grid items
## Expected behavior
One item is visible in the Grid items

**Comment by IvanDanchev** [comment]
Ticket id: 1424632
