### ISSUE TITLE
Native PanelBar doesn't work on Nuxt 3

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#421]
**Describe the bug**
The Native PanelBar component throws an error when used in Nuxt 3 context. 

**To Reproduce**
1. Open [this StackBlitz example](https://stackblitz.com/edit/nuxt-starter-neaobd?file=app.vue,layouts%2Fdefault.vue)
2. Try to expand the PanelBar
3. Check the browser's console

**Expected behavior**
The PanelBar should be expandable/collapsible with no errors in the console

**Screenshots**
<img width="1184" alt="image" src="https://github.com/telerik/kendo-vue/assets/41293735/21519dc9-294c-4050-954e-27abb0fca4e8">

**Comment by zdravkov** [comment]
Fixed in version 3.11.1 of Kendo UI for Vue - https://stackblitz.com/edit/nuxt-starter-6vuwcb
