### ISSUE TITLE
[Stepper] Missing StepProps

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#424]
**Describe the bug**

The following Stepper [StepProps](https://www.telerik.com/kendo-react-ui/components/layout/api/StepProps/) are not available in the API documentation of the StepProps:
- **successIcon**: String;
- **successSvgIcon**: Object;
- **errorIcon**: String;
- **errorSvgIcon**: Object;

**Expected behavior**
The above props should be added to the documentation.

**Comment by PekoPPT** [comment]
Once the above props are added, the Stepper and Wizard demos should be revised.

**Comment by zdravkov** [comment]
fixed https://www.telerik.com/kendo-vue-ui/components/layout/api/StepProps/
