### ISSUE TITLE
Grid's pager breaks when switching from display: none to display: block CSS definition

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#426]
**Describe the bug**
When we have a Grid that has a **display: none** CSS rule defined for it, switching to **display: block** makes the pager of the Native Grid be rendered in responsive mode as if the Grid is displayed on a small device.

Possible workaround:
- Set the pager's **responsive** property to **false**

**To Reproduce**
1. Open [this project](https://codesandbox.io/s/objective-alex-9s4nkp)
2. Click on the button

**Expected behavior**
The Grid should appear on the screen and its pager should look like this:
<img width="453" alt="image" src="https://github.com/telerik/kendo-vue/assets/41293735/75c48a3a-e873-40f6-ad11-b331bd0861b8">

while it is rendered like this:
<img width="219" alt="image" src="https://github.com/telerik/kendo-vue/assets/41293735/e4cc4cf0-89bb-4207-89b8-78124dbc32fb">

**Comment by zdravkov** [comment]
Fixed in version 3.12.0 - https://codesandbox.io/s/flamboyant-ellis-5jmqj5
