### ISSUE TITLE
Group header template displays "undefined" when grouped by Date field

### ISSUE THREAD

**Issue by veselints** [telerik/kendo-vue#44]
## I'm submitting a...
* Bug report

## Current behavior
Group header template displays "undefined" when grouped by Date field
For reference run the following StackBlitz: https://stackblitz.com/edit/4hwtep?file=index.js

## Expected behavior
Group header template should properly render the Date as a string

## Minimal reproduction of the problem with instructions
For reference run the following StackBlitz: https://stackblitz.com/edit/4hwtep?file=index.js

Browser:
- all

**Comment by Dimitar-Goshev** [comment]
Fixed in dev channel. The fix will be included in the next latest release.
