### ISSUE TITLE
[Bug] [Pager] [Grid] Pager responsiveness does not work

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#450]
Changing the width of the Pager (Grid) does not change the rendering of the Pager:

- https://stackblitz.com/edit/7wqhgz?file=src%2Fmain.vue

Additionally, In the following example the "info" part is initially missing and is shown after triggering resize:

- https://stackblitz.com/edit/vitejs-vite-t4wodt?file=src%2Fcomponents%2FHelloWorld.vue

**Comment by zdravkov** [comment]
Fixed in 3.14.1 - https://stackblitz.com/edit/7wqhgz-jv7k8j?file=src%2Fmain.vue
