### ISSUE TITLE
[Bug] [Grid,Pager] Pagable option "info" raises error on Nuxt3 Environment

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#451]
**Describe the bug**
When using the **info** option of the **pageable** Pager prop, on Nuxt 3, the following error appears:
![image](https://github.com/telerik/kendo-vue/assets/41293735/be4045ec-ed13-4afa-92b7-99397699a4c9)

**To Reproduce**
1. Open [this example](https://stackblitz.com/edit/nuxt-starter-evshuw?file=README.md)
2. Open the console

**Expected behavior**
No errors should appear and the pages info should be displayed

**Comment by zdravkov** [comment]
Fixed in 3.14.1 - https://stackblitz.com/edit/nuxt-starter-4wzr7p?file=package.json
