### ISSUE TITLE
[Bug][Scheduler] - Events are not rendered properly when using a slot template 

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#464]
When using a slot template the events are not rendered properly, this can be seen in the following demo:

https://codesandbox.io/s/tender-shape-lsm4cq

Ticket ID: 1626188

**Comment by elena-gancheva** [comment]
The fix is available in the latest official version [v4.1.0](https://github.com/telerik/kendo-vue-private/releases/tag/v4.1.0).
