### ISSUE TITLE
[Bug][TabStrip] CSS class name mismatch with the source of truth

### ISSUE THREAD

**Issue by NickIliev** [telerik/kendo-vue#476]
**Describe the bug**

The TabStrip Content item in Keno UI for Vue is styled through `k-content`

However, the kendo-themes sources of truth show that the class name should be `k-tabstrip-content`

**To Reproduce**

1. Use the Get Started demo and observe the CSS classes for the content item which is named `k-content`
![image](https://github.com/telerik/kendo-vue/assets/18008302/7fdde01f-fed4-4b0d-8fa6-f5d81c68f270)

**Expected behavior**
Instead `k-content` the class should be named `k-tabstrip-content` as per the source of truth
https://github.com/telerik/kendo-themes/blob/develop/tests/tabstrip/tabstrip.html 
![image](https://github.com/telerik/kendo-vue/assets/18008302/1d8be891-ab0c-4f24-b9e1-129cf489b3ce)

**Browser**
 - Kendo UI for Vue R3 2023
 - "@progress/kendo-vue-layout": "^4.1.0",

**Additional context**
Reported through t.1631394 - ThemeBuilder client

**Comment by NickIliev** [comment]
+ 1 from t.1631240

**Comment by PekoPPT** [comment]
Hey, @NickIliev. 

Thank you for your report. The issue has been fixed and the fix will be available with the next official version of Kendo UI for Vue.
I am now closing the issue but if there is something else related to it that you would like to discuss, please let us know.
