### ISSUE TITLE
[Bug][MultiSelect] Moving up/down with the keyboard fails after few items when virtualization is enabled

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#477]
1) Open the following example and focus the input:
- https://stackblitz.com/edit/nej2pu?file=src%2Fmain.vue
2) Move down with the arrow key
3) The focusing will stuck to "Item 7" even though the scrollbar is moved

**Comment by zdravkov** [comment]
Fixed in 4.3.2 of Kendo UI for Vue - https://stackblitz.com/edit/nej2pu-uvt6sb?file=src%2Fmain.vue
