### ISSUE TITLE
[Bug][Button] Changing from font icon to SVG icon changes the sizes of the button (missing k-icon-button class)

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#482]
Migrating from font icons to SVG icons for the Button causes change in the height and the width of the button (due to a missing "k-icon-button" class in the wrapping element):

- https://stackblitz.com/edit/sesmac?file=src%2Fmain.vue

**Comment by zdravkov** [comment]
fixed in version 4.3.0 of Kendo UI for Vue
