### ISSUE TITLE
[Bug][DropDownList] appendTo cannot be set via the popupSettings

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#483]
The appendTo property of the Popup component cannot be set for the DropDownList, when configured through the popupSettngs prop.

Reported in Ticket ID: 1632527

**Comment by michaelmano** [comment]
This is causing an issue with out application. https://www.telerik.com/forums/set-the-element-which-combo-box-uses-to-teleport-to

**Comment by filipKovachev** [comment]
Reported again in Ticket ID: 1638380

**Comment by PekoPPT** [comment]
Hi, @michaelmano & @filipKovachev .

In version [4.3.3-dev.202404190617](https://www.npmjs.com/package/@progress/kendo-vue-common/v/4.3.3-dev.202404190617) we exposed multiple properties(including the appendTo) for the popup of all DropDowns. These properties are configurable through the **popupSettings** property of each dropdown. Most probably, the new configuration options will be officially released next week.
