### ISSUE TITLE
[Bug][Licensing] License cannot be activated with Node 21.3.0

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#487]
**Describe the bug**
The following error appears when activating the license of the Native Vue suite with Node 21.3.0
![image](https://github.com/telerik/kendo-vue/assets/41293735/ac2c5a16-5e88-442e-b526-380046920cbc)

**To Reproduce**
1. Install node **21.3.0**
2. Run `npx kendo-ui-license activate`
3. See the unsuccessful activation error

**Expected behavior**
The license activation should work with all Node versions

**Comment by tsvetomir** [comment]
Seems to be limited to 21.3, works fine in 21.4

We should always recommend customers to use an `ACTIVE` or `MAINTENANCE` [Node.js releases](https://nodejs.org/en/about/previous-releases).

**Comment by PekoPPT** [comment]
The current issue is no longer replicable with version 21.4.0 of Node. Please use a version of Node different from 21.3.0.
