### ISSUE TITLE
Content-Security-Policy (CSP) strict mode support

### ISSUE THREAD

**Issue by fabiano** [telerik/kendo-vue#49]
## I'm submitting a...

- Question

## Current behavior

I'm trying to add more strict CSP rules to my app and we use the Grid component. One of the dependencies is the @progress/kendo-vue-popup package and it's raising unsafe-inline errors (there are some methods in the package that manually set the style of the elements).

Do you have plans to make the Kendo Vue library CSP strict compatible?

## Expected behavior

The components work with strict CSP rules.

## What is the motivation or use case for changing the behavior?

I want to use strict CSP rules for the script and styles.

## Environment

Package versions:

+-- @progress/kendo-data-query@1.5.2
+-- @progress/kendo-theme-default@4.11.1
+-- @progress/kendo-vue-animation@0.4.4
+-- @progress/kendo-vue-grid@0.4.4
+-- @progress/kendo-vue-intl@0.4.4
+-- @progress/kendo-vue-popup@0.4.4
+-- @vue/cli@4.1.2
+-- @vue/cli-service-global@4.1.2
`-- vue-class-component@7.2.2

System:
- Node version: v12.13.1
- Platform:  Windows

## Minimal reproduction of the problem with instructions

1. git clone https://github.com/fabiano/kendo-vue-grid-csp
2. cd kendo-vue-grid-csp
3. npm install
4. npm start
5. Open the Developer Tools and you will see the error message: `Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-Y+wsDhnso/VitFKVAmAGIC+CGwKJuRUiycQ54atO+eE='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by zdravkov** [comment]
Thank you for reporting the issue.

We will do our best to research the issue and think for possible solutions yet for a better clarity of the issue would you please provide a sample project or a stackblitz example where we could observe the exact CSP rule, Kendo code and error so we could research it deeper.

Regards,
Plamen

**Comment by fabiano** [comment]
@zdravkov I updated my initial post with the instructions to reproduce the error

**Comment by zdravkov** [comment]
Thank you for your effort. We will research it deeper and will share status updates here in the issue.
