### ISSUE TITLE
[Bug][DropDownList] No data template throws warning

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#491]
**Describe the bug**
Currently when using a no-data template with the DropDownList the following warning is thrown multiple times:
```
chunk-B27BRMRB.js?v=34fcf657:1615 [Vue warn]: Extraneous non-props attributes (attrs, on) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <List id="f457bb51-402d-48af-b65a-4e77e8e69d0e" attrs=undefined show=undefined  ... > 
  at <Popup ref="popup" style= {width: undefined, direction: undefined} popupClass="k-list-container"  ... > 
  at <ListContainer ref="container" onMousedown=fn<preventDefaultNonInputs> on=undefined  ... > 
  at <KendoDropDownList key=0 ref="el" data-items= []  ... > 
  at <HelloWorld msg="Vite + Vue" > 
  at <App>
````

**To Reproduce**
1. Open the following example: https://stackblitz.com/edit/vitejs-vite-mc7nrd?file=src%2Fcomponents%2FHelloWorld.vue
2. Click on the count is button and observe that the warning is thrown multiple times

**Expected behavior**
No warnings should be thrown

Reported in Ticket ID: 1634123

**Comment by PekoPPT** [comment]
The bug fix will be available in our next official version - 4.1.1 - which should be released by the end of the year.
