### ISSUE TITLE
[Bug][Menu] The MenuItemModel has String type for the svgIcon, but it accepts only SvgIcon type

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#502]
**Describe the bug**
The "items" property of the Menu accepts an array of MenuItemModel. The MenuItemModel has "svgIcon" property that is currently String type, but in order to render an icon, an SvgIcon must be set to the property, which makes it impossible to set icon and use the MenuItemModel

**To Reproduce**

`import { gearIcon } from "@progress/kendo-svg-icons";`

```
const menuData: MenuItemModel[] = [
{"text": "Item1", "svgIcon": gearIcon}
];
```
`<Menu :items="menuData" />`

There will be TypeScript error on build

**Expected behavior**
The svgIcon type in the MenuItemModel must be changed to support SvgIcon and not string

**Additional context**
version: 4.2.0

**Comment by zdravkov** [comment]
fixed in version 4.3.0 of Kendo UI for Vue
