### ISSUE TITLE
[Bug][Charts] legendItemLeave event is not triggered

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#503]
**Describe the bug**

Currently the legendItemLeave event is not triggered: https://www.telerik.com/kendo-vue-ui/components/charts/api/LegendItemLeaveEvent/

**To Reproduce**
1. Open this sample: https://stackblitz.com/edit/co2rkp-mwge1z?file=src%2FPageViews.vue
2. Notice that the `legendItemLeave ` event does not work

**Expected behavior**
The legendItemLeave event should work.

**Comment by zdravkov** [comment]
The issue is fixed in v4.3.1 of Kendo UI for Vue: https://stackblitz.com/edit/co2rkp-qu19ia?file=src%2Fmain.vue
