### ISSUE TITLE
[Bug][RadioGroup] selectors are not rendered in the DOM

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#520]
**Describe the bug**
The RadioGroup has the following selectors that are used for accessibility: https://www.telerik.com/kendo-vue-ui/components/inputs/radiogroup/accessibility-docs/wai-aria-support/#toc-wai-aria

However they are not currently rendered in the DOM for the component.

**To Reproduce**
1. Open this StackBlitz example: https://stackblitz.com/edit/lp78au-p85meq?file=src%2Fmain.vue
2. Inspect the DOM and notice that `k-radio-item` and the rest are not rendered

![image](https://github.com/telerik/kendo-vue/assets/92358162/9449d752-78df-4a92-913d-0ca31d98a90b)

**Expected behavior**
The listed selectors should be present in the DOM

Reported in Ticket ID: 1641118

**Comment by zdravkov** [comment]
The issue is fixed in v4.3.1 of Kendo UI for Vue - https://stackblitz.com/edit/lp78au-jfym9r
