### ISSUE TITLE
Drawer `navigation-header` and `navigation-footer` only starts appearing after toggling the drawer once.

### ISSUE THREAD

**Issue by PindaPixel** [telerik/kendo-vue#534]
**Describe the bug**
When defining a custom header for the `Drawer` component, the header only appears after toggling the open state of the drawer after initial mount. This is most notable when `mini` is set to true, or when the initial state of the drawer is expanded.

**To Reproduce**

https://stackblitz.com/edit/swzwuv?file=src%2Fmain.vue

1) Notice the header is not being rendered
2) Open the drawer
3) Notice the header popping in

**Expected behavior**
The header should render immediately on mounting the component.

**Screenshots**

**Browser**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: 122, 123

**Additional context**
In the current situation when the initial state of the drawer is open, it needs to be closed before the header or footer start appearing.

**Comment by PekoPPT** [comment]
Hi, @PindaPixel. Thank you for sharing the issue with us. I can confirm that the described behavior is a bug. 

The issue is already in our backlog and we will do our best to fix it in the next few weeks.

**Comment by PekoPPT** [comment]
Hello, everyone. 

The bug is fixed and the fix will be available with the next release of Kendo UI for Vue. 
We currently don't have a specific date for the next patch release but it will probably be available within the next two weeks.
