### ISSUE TITLE
[Bug][Scheduler] Slot cells are misaligned from the headers

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-vue#535]
**Describe the bug**
The slot cells of the Scheduler are misaligned from the column headers as of version 3.10.2
![image](https://github.com/telerik/kendo-vue/assets/6196386/6e36192c-04ab-45b3-9d3d-7cdb6b54ee81)

**To Reproduce**

1. Go to https://stackblitz.com/edit/xccqnp-nnelqf?file=package.json

**Expected behavior**
Downgrade to v3.10.0 - https://stackblitz.com/edit/xccqnp-3cwxfp?file=package.json
![image](https://github.com/telerik/kendo-vue/assets/6196386/8a54d01e-93d7-4285-8431-746e825a2fdc)

**Additional details**
Reported in Ticket ID: 1644502

**Comment by zdravkov** [comment]
Fixed in version 4.3.2 of Kendo UI for Vue
