### ISSUE TITLE
[Bug][Grid] Checkbox wrap is exposed instead of Checkbox

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#536]
**Describe the bug**
Currently we are sending the entire wrap in the custom event instead of the input 
**To Reproduce**
1. Open this example: https://stackblitz.com/edit/zsqzyz-4nw3fb?file=src%2Fmain.vue
2. Click on the :D span and observe that `k-checkbox-wrap` is being shown
![image](https://github.com/telerik/kendo-vue/assets/92358162/c7105a3b-ed1a-4201-a6b4-05e8c0d46edc)

**Expected behavior**
checkbox should be rendered instead as it was in the previous version

![image](https://github.com/telerik/kendo-vue/assets/92358162/72aeec06-cf44-4f81-97c7-1860f529e171)

Ticket ID: 1643888

**Comment by zdravkov** [comment]
Fixed in version 4.3.2 of Kendo UI for Vue - https://stackblitz.com/edit/zsqzyz-iem4ip?file=src%2Fmain.vue
