### ISSUE TITLE
[Bug][Scheduler] slotRender does not pass start, end and range values for the slot 

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#545]
**Describe the bug**
The slotRender should provide all props from the SchedulerSlot, but currently it passes only a small set of properties. For example, start, end and range values are missing.

**To Reproduce**
In the following example, the props.start is not available:
https://stackblitz.com/edit/szhenq?file=src%2Fmain.vue

**Expected behavior**
All of the SchedulerSlot props should be available within the slotRender

**Version**
4.3.1

**Comment by zdravkov** [comment]
Fixed in version 4.3.2 of Kendo UI for Vue - https://stackblitz.com/edit/szhenq-nbvtqs?file=src%2Fmain.vue
