### ISSUE TITLE
[Bug][Scheduler] Misalignment in the Agenda view

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#546]
**Describe the bug**
The columns in the Agenda view are misaligned.

**To Reproduce**
In the following example can observe that the columns in the header and the content are misaligned:

- https://stackblitz.com/edit/zyrlhv?file=src%2Fmain.vue

**Expected behavior**
The columns should align correctly
(reference: https://www.telerik.com/kendo-react-ui/components/scheduler/views/agenda/)

**Version**
4.3.1

**Comment by zdravkov** [comment]
Fixed in version 4.3.2 of Kendo UI for Vue
