### ISSUE TITLE
[Bug][Grid] The columnMenu icon should be changed to dots instead of filter icon and the title text should not go under the icon

### ISSUE THREAD

**Issue by kdikov82** [telerik/kendo-vue#554]
**Describe the bug**
(applicable for KendoReact Grid as well)
The columnMenu icon should be changed from a filter icon to dots (as in angular and jQuery: https://www.telerik.com/kendo-angular-ui/components/grid/accessories/column-menu/), since the menu is not used only for filtering.

Additionally, if the width of the column is not enough to display the entire title and the icon, the title text will go under the icon, which is not visually pleasing. 

**To Reproduce**
https://stackblitz.com/edit/eaa6m8?file=src%2Fmain.vue

Version: 4.3.2

**Comment by PekoPPT** [comment]
The issue with the icon of the column menu is fixed and will be available with our next official release. The issue with the overlapping column text and the menu is moved to [this new issue](https://github.com/telerik/kendo-vue/issues/558) and will be handled separately.
