### ISSUE TITLE
[Bug][DatePicker] Datepicker mask doesn't work properly in vue version 3.4.0 and higher

### ISSUE THREAD

**Issue by danyavol** [telerik/kendo-vue#563]
**Describe the bug**
In Vue version 3.4.0 and higher manual date change using keyboard doesn't work as expected. User is able to enter a non-number chracter or even erase the whole mask using Backspace.

**To Reproduce**
1) Open the following CodeSandbox https://codesandbox.io/p/sandbox/relaxed-sky-nx3m2d
2) Open package.json and update "vue" version to "3.4.0"
3) Focus on date picker input and press any non-number key on your keyboard. Press Backspace multiple times

**Expected behavior**
Datepicker mask works the same as with Vue v3.3.13. It is not possible to erase the mask ("month/day/year"). Non-number characters are ignored.

**Screenshots**
![image](https://github.com/telerik/kendo-vue/assets/48417874/43dbaf16-e761-4435-a24f-8669b0ac26ae)
![image](https://github.com/telerik/kendo-vue/assets/48417874/436c75dc-beef-4223-a2b1-dc5fa9a02b0c)
![image](https://github.com/telerik/kendo-vue/assets/48417874/bb6a7a7f-b84e-4ea0-bf29-2c943b0e8c6d)
![image](https://github.com/telerik/kendo-vue/assets/48417874/e8e466ac-ff08-4c4a-9ee3-09659c1cc393)

**Browser**
 - OS: Windows
 - Browser: Chrome
 - Version: 123

**Additional context**
It stopped working since vue version 3.4.0 and still not working in the latest 3.4.23. Version of kendo packages - latest.
![image](https://github.com/telerik/kendo-vue/assets/48417874/42a1a738-a12c-4bff-bacb-db654c190098)

**Comment by PekoPPT** [comment]
Hi, @danyavol .
Thank you for your report! 

The bug is fixed and the fix will be available with version 5.0.0. of the Kendo UI for Vue suite which will be released by May 15. 

Once the new version is out, you can update your project. 
Please let me know if you need further assistance with the issue.
