### ISSUE TITLE
[Bug][TextBox] readonly props does not work

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#566]
**Describe the bug**
Currently setting the readonly props to true does not take any effect. However, when you inspect the rendered input it has its readonly set:
![image](https://github.com/telerik/kendo-vue/assets/92358162/34ae0e49-8752-4b3d-90be-186841b6d5bc)

**To Reproduce**
1. Open this example: https://stackblitz.com/run/?file=src%2Fmain.vue
2. Observe that the TExtBox is not shifting to a readonly state. Setting the prop to true or false does change in the HTML but it does not take effect.

**Expected behavior**
Setting the prop to true should make the component readonly

Ticket ID: 1650106

**Comment by zdravkov** [comment]
It seems like the readonly prop is not written with English letters and that is why it is not working correctly in the example. Here is an example that shows both components and that it works correctly when it is written in English - https://stackblitz.com/edit/e74stb-wjaxgb?file=src%2Fmain.vue
