### ISSUE TITLE
[Bug][DropDownTree] Menu does not close when using filtering

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#575]
**Describe the bug**
DropDownTree cannot be closed when using filtering

**To Reproduce**
1. Open this example: https://stackblitz.com/edit/rcfd7m-u4c8jp?file=src%2Fmain.vue
2. Select an item and click outside the component. Notice that you cannot close it

**Expected behavior**
When clicking outside the DropDownTree should close.

Reported in Ticket ID: 1651541, 1653645, 1655131

**Comment by zdravkov** [comment]
fixed in the latest Kendo UI for Vue release
