### ISSUE TITLE
add possibility to set hidden to the sub columns

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#60]
## I'm submitting a...

* Bug report 

## Current behavior
We can only set 'hidden' to the root columns 

## Expected behavior
We should also be able to set hidden to the sub columns

**Comment by onlife2007** [comment]
Hi, is there any progress on this issue? I'm looking for it

**Comment by zdravkov** [comment]
The feature is already released in the 0.5.2 version of Kendo UI for Vue an you can see an example here - https://stackblitz.com/edit/kntamg-qwdfzc
