### ISSUE TITLE
add footer cell property 

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#61]
Add possibility to define custom footer for the column similar to the one the  we have in our React Grid - https://www.telerik.com/kendo-react-ui-develop/components/grid/cells/#toc-footer-cells

**Comment by onlife2007** [comment]
Hi, is there any progress on this issue? I'm looking for it

**Comment by zdravkov** [comment]
The feature is already released in the 0.5.2 version of Kendo UI for Vue an you can see an example here - https://stackblitz.com/edit/fqgeqc-6gztmq.
