### ISSUE TITLE
Resizing locked columns is not working as expected

### ISSUE THREAD

**Issue by fabiano** [telerik/kendo-vue#62]
## I'm submitting a...

* Bug report

## Current behavior

When having two or more locked columns, resizing the first locked column is moving the other columns to behind the locked columns.

## Minimal reproduction of the problem with instructions

1. Open https://stackblitz.com/edit/x8lmaf?file=index.js
2. Resize the Name column

![image](https://user-images.githubusercontent.com/2686/76749700-b5eb4100-675b-11ea-9b64-d8b0b07b3c8d.png)

## Environment

Package versions:

See https://stackblitz.com/edit/x8lmaf?file=package.json.

Browser:

- Chrome (desktop) version 80.0.3987.132
- Firefox version 74.0
- Edge Canary version 82.0.453.0

System:

- Platform:  Windows

**Comment by zdravkov** [comment]
In such scenario we need to use the 'columnresize' emitted event and update the columns manually so the could calculate the width and the locked position correctly. Here is and updated example against the latest version of Kendo UI for Vue - https://stackblitz.com/edit/hmsoaa?file=src%2Fmain.vue
