### ISSUE TITLE
[Bug][Scheduler] Events in MonthView cover the date

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#620]
**Describe the bug**
Currently when using the MonthView the event covers the date. The bug is a regression one and is introduced in version `3.3.0`.

**To Reproduce**
1. Open this stackblitz: https://stackblitz.com/edit/4qny17?file=src%2Fmain.vue
2. Observe how the date number is not visible, because the event covers it:
![image](https://github.com/user-attachments/assets/eaa468e9-4ca9-4075-b1ed-d173d007d244)

**Expected behavior**
The date should be visible, the same way it is for KendoReact and other suites.

Ticket ID: 1663965

**Comment by Yanko-Georgiev** [comment]
Also reported in ticket: 1665514

**Comment by zdravkov** [comment]
Fixed in the latest dev versin of Kendo Ui for Vue - https://stackblitz.com/edit/4qny17-tjmrm1?file=package.json. Will be included in the next official npm version that is expected in a few days.
