### ISSUE TITLE
[Bug][Chart] A warning is thrown when the ChartNavigatorCategoryAxis name is set to a string

### ISSUE THREAD

**Issue by vveesseelliinnaa** [telerik/kendo-vue#622]
**Describe the bug**
A warning is thrown when the ChartNavigatorCategoryAxis name is set to a string. It seems that the prop expects an object:

![image](https://github.com/user-attachments/assets/d8105576-4e23-425f-ac7d-22ec79a9164d)

**To Reproduce**
1. Open https://stackblitz.com/edit/ysshnm?file=src%2Fmain.vue%3AL26
2. Open the console and observe the thrown warning

**Expected behavior**
The ChartNavigatorCategoryAxis name prop should accept string values.

**Additional details**
Reported in Ticket ID: 1665725

**Comment by PekoPPT** [comment]
The issue is fixed and the fix will be available with one of the following releases of the Kendo UI for Vue suite.
