### ISSUE TITLE
[Bug][Grid] When using a checkbox ` k-checkbox-wrapper` is rendered twice

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-vue#625]
**Describe the bug**
When trying to override and use a checkbox it's printing the `k-checkbox-wrapper` element twice.

**To Reproduce**
1. Open this example:  https://stackblitz.com/edit/zsqzyz-6m38oi?file=src%2Fmain.vue
2. Observe in the rendered markup:
![image](https://github.com/user-attachments/assets/d85b17f0-d13f-44a1-a81a-3c519f9034d8)

**Expected behavior**
 No `k-checkbox-wrap` to be rendered and slot to be checkbox not `k-checkbox-wrap`

Ticket ID: 1643888

**Comment by zdravkov** [comment]
Fixed in the latest dev version of Kendo UI for Vue - https://stackblitz.com/edit/zsqzyz-jzanpa
It will be available in the next official version of the components
