### ISSUE TITLE
[BUG][Dialog]The `className` prop content removes `k-dialog-wrapper` class

### ISSUE THREAD

**Issue by InaGlushkova** [telerik/kendo-vue#629]
**Describe the bug**
When we use the `className` property of the Dialog to apply additional styling the the wrapping div element the `k-dialog-wrapper` class gets removed.

**To Reproduce**

  1. Open the following [Stackblitz example](https://stackblitz.com/edit/rkudfu-4xnzsy?file=src%2Fmain.vue)
  2. Search the dom tree for the `mycustom-class`, applied using the `className` property
  3. The `k-dialog-wrapper` class has been removed

**Expected behavior**
The new class name should be added to the existing `k-dialog-wrapper` class instead of replacing it.

**Possible workaround**
Use `:className`="'k-wrapper-dialog your-custom-style-here'"

Reported under ticket ID: 1669567.

**Comment by zdravkov** [comment]
fixed in the latest version of Kendo UI for vue - https://stackblitz.com/edit/rkudfu-uxpeko?file=src%2Fmain.vue
