### ISSUE TITLE
IE11 grid saveAsExcel()  not support ?

### ISSUE THREAD

**Issue by ljlm0402** [telerik/kendo-vue#69]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Current behavior

Isn't IE11 grid saveAsExcel () supported? No response in browser. For reference, it worked fine in Chrome.

URL : https://docs.telerik.com/kendo-ui/api/javascript/ui/grid/methods/saveasexcel?_ga=2.206290579.1477628129.1587343010-431391752.1585013881

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by zdravkov** [comment]
Hi @ljlm0402 ,

I have just tested the saveAsExcel() method in IE11 and it worked correctly at my side in this dojo - https://dojo.telerik.com/@zdravkov/EZInADUL. 

Here is a gif of my test:
![saveAsExelIE](https://user-images.githubusercontent.com/9494406/80607032-a9862380-8a3d-11ea-82dc-edbd1aeb9d84.gif)
If our scenario is somehow different please elaborate it or provide a runnable sample.

Greetings,
Plamen
