### ISSUE TITLE
footerCell is not shown when the column is hidden and then shown again

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#70]
* Bug report 

## Current behavior
https://stackblitz.com/edit/jjinj9-dzgbtz?file=index.html
Click the hide button in the UnitPrice column
Click the Restore hidden columns button
The footer of the UnitPrice is not visible

## Expected behavior
The footer of the UnitPrice is visible

**Comment by onlife2007** [comment]
Do you have any update on this?

**Comment by zdravkov** [comment]
Thank you for getting in touch - we have moved it in a 'in progress' state.
