### ISSUE TITLE
Add on-week-click event to calendar

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#73]
Currently there is no direct click event of the CalendarWeekCell - we can add such event for avoid the need to create custom cell only to add a click for the cell.

**Comment by joingenor** [comment]
Is it possible to add a on click event to the weekday name column in calendar. 
![image](https://user-images.githubusercontent.com/3841752/98522841-74bd1980-2275-11eb-8b91-d9072e774d36.png)

**Comment by zdravkov** [comment]
Both 'weekcellclick' and 'weeknameclick' events are available in the 1.1.5 version of the component - https://stackblitz.com/edit/vo7dum?file=src/main.vue
