### ISSUE TITLE
Wrong initial value of DropDownList with custom rendering

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-vue#76]
## I'm submitting a...
* Bug report

## Current behavior
The first country - Albania - is selected in the dropdown, but it does not appear as selected in the closed DropDownList template.
Clicking on the expanded Albania or pressing Enter does not select it, which confirms that it is currently selected, but not visible in the template.

## Expected behavior
The first country - Albania - is selected in the dropdown and in the closed DropDownList template

## Minimal reproduction of the problem with instructions
1. Open in StackBlitz the [DropDownList - Custom Rendering - Values example](https://www.telerik.com/kendo-vue-ui/components/dropdowns/dropdownlist/custom-rendering/#toc-values)

## Environment
Package versions:
  "dependencies": {
    "vue": "2.6.11",
    "@progress/kendo-vue-grid": "1.0.3",
    "@progress/kendo-vue-data-tools": "1.0.3",
    "@progress/kendo-vue-dropdowns": "1.0.3",
    "@progress/kendo-vue-dateinputs": "1.0.3",
    "@progress/kendo-vue-dialogs": "1.0.3",
    "@progress/kendo-vue-inputs": "1.0.3",
    "@progress/kendo-drawing": "1.8.1",
    "@progress/kendo-vue-intl": "1.0.3",
    "@progress/kendo-data-query": "1.5.4",
    "@progress/kendo-vue-excel-export": "1.0.3",
    "@progress/kendo-vue-pdf": "1.0.3",
    "@progress/kendo-vue-animation": "1.0.3",
    "@progress/kendo-vue-popup": "1.0.3"
  }

Browser: all

**Comment by zdravkov** [comment]
The correct behavior in this case is to use 'value' instead of current value - here is a demo with the fixed version - https://stackblitz.com/edit/hjmbcg-t743ku?file=package.json
