### ISSUE TITLE
kendo.culture('en-US') not work by manually in kendo ui for vue.

### ISSUE THREAD

**Issue by lever1225** [telerik/kendo-vue#79]
## I'm submitting a...

* Regression report 
* Bug report 
* Suggestion for improvement
* Documentation issue or request

## Environment

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by zdravkov** [comment]
Hi,
In general kendo.culture is dedicated only for the Vue Wrappers and you can find an example with working kendo.culture  - https://stackblitz.com/edit/d9bdc2-m9mdde?file=src%2Fmain.vue.

Please have in mind that this is only working for Kendo Wrappers for Vue - for the Native Kendo Vue components we use another approach as for example it is shown here - https://www.telerik.com/kendo-vue-ui/components/grid/.

Greetings,
Plamen
