### ISSUE TITLE
The icon-class property is missing in the implementation of the wrapper Button component 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#82]
## I'm submitting a product enhancement. 
* Suggestion for improvement

## Current behavior
Currently, the[ icon-class property ](https://www.telerik.com/kendo-vue-ui/components/buttons/api/button/Button/#icon-class)cannot be used in the configuration of the Button component. 

## Expected behavior
The icon-class property should be available for usage as it is in the Kendo UI for jQuery suite

## Minimal reproduction of the problem with instructions
1. Open [this StackBlitz example ](https://stackblitz.com/edit/creylk-w75avp?file=src%2Fmain.vue)
1. The button on the left side uses the icon-class property, but there is no icon added to it 

## What is the motivation or use case for changing the behavior?
Unify the Wrappers components with the same functionalities as the Kendo UI for jQuery components.

**Comment by zdravkov** [comment]
Added in version  "@progress/kendo-buttons-vue-wrapper": "2020.3.1022" - https://stackblitz.com/edit/creylk-fpxwgy?file=package.json
