### ISSUE TITLE
TypeError: kendo.jQuery(...).kendoSwitch is not a function

### ISSUE THREAD

**Issue by felipe-allmeida** [telerik/kendo-vue#83]
## I'm submitting a...

* Bug report

## Current behavior
![image](https://user-images.githubusercontent.com/62676728/98272623-0ffd7880-1f70-11eb-82cf-024110fca041.png)
![image](https://user-images.githubusercontent.com/62676728/98272492-e93f4200-1f6f-11eb-9263-c8544b9aee63.png)

Kendo switch wrapper for typescript is not working as expected. It is always throwing the error that kendoSwitch is not a function. I'm using other wrappers as the multiselect and the tooltip and they're both working just fine.

I'm importing the wrapper on my main.ts 
![image](https://user-images.githubusercontent.com/62676728/98272556-fd833f00-1f6f-11eb-9d66-401e60510d91.png)

Then on my component:

![image](https://user-images.githubusercontent.com/62676728/98272846-5521aa80-1f70-11eb-9147-f8a4d47ffb88.png)

## Expected behavior
It should show the switch toogle correctly.

![image](https://user-images.githubusercontent.com/62676728/98272714-273c6600-1f70-11eb-8678-fe091ec81b45.png)

## Environment

Package versions:
| package  | version  |
|---|---|
| vue  | 2.6.12  |
| @progress/kendo-dropdowns-vue-wrapper  | 2020.3.928 |
| @progress/kendo-inputs-vue-wrapper | 2020.3.1022 |
| @progress/kendo-ui | 2020.3.915  |
| @progress/kendo-vue-dropdowns | 1.1.2 |
| @progress/kendo-vue-intl  | 1.1.2  |
```

```

Browser:
- Microsoft Edge (desktop) version 86.0.622.61

System:
- TypeScript version: 4.0.3
- Node version: v14.7.0
- Platform:  Windows

**Comment by ronaldohoch** [comment]
Wow!
I came here to look this exactly error! I'm using typescript on my project and i can't made it work

**Comment by zdravkov** [comment]
Hi all,

Thank you for reporting the issue. I have tried to replicate it in a simple project but to no avail. Here is my test project:
[vue2-typescript-switch.zip](https://github.com/telerik/kendo-vue/files/5545203/vue2-typescript-switch.zip)

Would you please review it and let me know what else should I add or do in order to replicate the issue?

Regards,
Plamen

**Comment by felipe-allmeida** [comment]
@zdravkov Just downloaded your project. The only thing that is different on my project, is that the `Vue.use(InputInstaller)` is not directly in the component, it is in the App.vue file.

Now I ask you, the correct way is to use it inside the component?

Regards,
Felipe

**Comment by zdravkov** [comment]
Hi Filipe,

In theory there should be no difference if you use it in the component or in the App.vue file. I have updated my project to use it in the App.vue file and still everything is working correctly.
[vue2-typescript-switch2.zip](https://github.com/telerik/kendo-vue/files/5546330/vue2-typescript-switch2.zip)
If you find out any other difference in the scenarios please let me know.

Regards,
Plamen

**Comment by zdravkov** [comment]
Closing the issue because we could not replicate it so far. If you still observe it please elaborate the scenario so we could review it once again.
