### ISSUE TITLE
The locked multicolumn header of the native Gird moves on horizontal scrolling

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#84]
## Current behavior
In a Native Grid that has a multicolumn header which is locked, when the Grid is scrolled horizontally, the upper(shared) part of the multicolumn header is moving based on the scrolling direction. 

## Expected behavior
When the multicolumn header is locked it should not move along with the horizontal scrolling inside the Grid

## Minimal reproduction of the problem with instructions
1. Open [this example](https://stackblitz.com/edit/qjgucz-ic78ny?file=src%2Fmain.vue)
2. Scroll the Grid horizontally

**Comment by zdravkov** [comment]
Fixed in 2.1.1 - https://stackblitz.com/edit/qjgucz-nkxnhu?file=src%2Fmain.vue
