### ISSUE TITLE
Native DatePicker calendar popup closes after pressing the navigation arrow (iOS 14.1)

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#85]
## Current behavior
When the DatePicker popup calendar is opened on a device with iOS 14.1, once the navigation arrow is clicked, the pop immediately closes

## Expected behavior
Tapping on the navigation arrow should change the current calendar view and remain the popup opened. 

## Minimal reproduction of the problem with instructions
1. Open [this demo](https://www.telerik.com/kendo-vue-ui/components/dateinputs/datepicker/) on a mobile device with iOS 14.1
1. Open the calendar of the DatePicker and navigate it with the navigation arrows

**Comment by PekoPPT** [comment]
Also reported in ticket 1509433

**Comment by PekoPPT** [comment]
The bug is also replicable when the user is in a "Select year" mode and click on the space below the available years:
![image](https://user-images.githubusercontent.com/41293735/109938482-bc5e2a00-7cd8-11eb-8f8b-8154dcba9cfe.png)

**Comment by zdravkov** [comment]
The IOS issue is fixed in 2.1.3 version https://stackblitz.com/edit/v9qg1f?file=package.json.
The issue with the click in the space below the cells is a separate one so we moved it in a separate issue [here](https://github.com/telerik/kendo-vue/issues/100).
