### ISSUE TITLE
Types of DropDownList (and Possibly others) are not correct for Vue 3

### ISSUE THREAD

**Issue by timritzer** [telerik/kendo-vue#89]
I am not yet a paying customer, but am in evaluation to use Kendo for our UI front end, and am in our trial period. We are running into issues using the Vue components with Vue 3, despite the docs saying they are supported. We will likely have to hack around this, but wanted to leave feedback that this is a sharp edge that really is causing us pain.

* Bug report

## Current behavior
The type of the DropDownList is currently any, because the Vue imports are pointing to the old, Vue 2 structure.
For DropDownList, this is kendo-vue-dropdowns/src/DropDownList/DropDownList.tsx

```
import { RecordPropsDefinition, ComponentOptions } from 'vue/types/options';
```
Vue now has ComponentOptions in just vue, and RecordPropsDefinition does not even exist.

This causes us to lose all downstream type safety, even though the components are functional. This most effects our tests, where everything is a mess when interacting with Kendo.

## Expected behavior
The types would be correct, even if we had to load a second type package to support the newer Vue version.

## Minimal reproduction of the problem with instructions
Create new Vue 3 project with typescript support, and install kendo-vue-dropdowns, and try looking at the type of DropDownList

## What is the motivation or use case for changing the behavior?
Being able to combine Vue, Typescript, and Kendo ui controls

## Environment

Package versions:
```
+-- @auth0/auth0-spa-js@1.13.5
+-- @progress/kendo-buttons-vue-wrapper@2020.3.1118
+-- @progress/kendo-data-query@1.5.4
+-- UNMET PEER DEPENDENCY @progress/kendo-drawing@^1.6.0
+-- @progress/kendo-popups-vue-wrapper@2020.3.1118
+-- @progress/kendo-theme-default@4.27.0
+-- @progress/kendo-ui@2020.3.1118
+-- @progress/kendo-vue-animation@1.2.0
+-- @progress/kendo-vue-data-tools@1.2.0
+-- UNMET PEER DEPENDENCY @progress/kendo-vue-dateinputs@^1.2.0
+-- @progress/kendo-vue-dialogs@1.2.0
+-- @progress/kendo-vue-dropdowns@1.2.0
+-- @progress/kendo-vue-grid@1.2.0
+-- @progress/kendo-vue-inputs@1.2.0
+-- @progress/kendo-vue-intl@1.2.0
+-- @progress/kendo-vue-popup@1.2.0
+-- @types/jest@26.0.18
+-- @typescript-eslint/eslint-plugin@4.9.1
+-- @typescript-eslint/parser@4.9.1
+-- @vue/cli-plugin-eslint@4.5.9
+-- @vue/cli-plugin-router@4.5.9
+-- @vue/cli-plugin-typescript@4.5.9
+-- @vue/cli-plugin-unit-jest@4.5.9
+-- @vue/cli-plugin-vuex@4.5.9
+-- @vue/cli-service@4.5.9
+-- @vue/compiler-sfc@3.0.4
+-- UNMET PEER DEPENDENCY @vue/composition-api@^1.0.0-beta.1
+-- @vue/eslint-config-prettier@6.0.0
+-- @vue/eslint-config-typescript@7.0.0
+-- @vue/test-utils@2.0.0-beta.12
+-- @vuelidate/core@2.0.0-alpha.8
+-- @vuelidate/validators@2.0.0-alpha.5
+-- bootstrap@4.5.3
+-- UNMET PEER DEPENDENCY eslint@7.15.0
+-- eslint-plugin-prettier@3.2.0
+-- eslint-plugin-vue@7.2.0
+-- jest@26.6.3
+-- jest-editor-support@27.2.0
+-- jest-serializer-vue@2.0.2
+-- node-waves@0.7.6
+-- popper.js@1.16.1
+-- prettier@2.2.1
+-- sass@1.27.0
+-- sass-loader@8.0.2
+-- ts-jest@26.4.4
+-- typescript@4.1.2
+-- vue@3.0.4
+-- vue-jest@5.0.0-alpha.5
+-- vue-router@4.0.1
`-- vuex@4.0.0-rc.2
```

Browser:
N/A

System:
- TypeScript version: 4.1.2
- Node version: v12.19.0
- Platform:  Windows

**Comment by zdravkov** [comment]
Hi @timritzer ,

Thank you for reporting this - it is definitely an issue and will look at it but would you please elaborate a little bit what are the exact steps to see the exact errors/ warnings that you see at our side.
I am attaching a sample test project that I tested but could not replicate the error.

[vue3-typescript-tests.zip](https://github.com/telerik/kendo-vue/files/5673310/vue3-typescript-tests.zip)

Regards,
Plamen

**Comment by timritzer** [comment]
Not sure how to illustrate the issue without screenshots, so here is what is happening:

Inside your node module, the types are not loading because the paths are wrong. This causes the typescript compiler to lose type information.
![Screen Shot 2020-12-10 at 2 30 02 PM](https://user-images.githubusercontent.com/7315207/101829058-07acd600-3af8-11eb-98f4-5250e29bfecf.png)

So downstream, like in tests if I try to use the types of your controls, they are of type any, meaning no type safety are available.
![Screen Shot 2020-12-10 at 2 29 24 PM](https://user-images.githubusercontent.com/7315207/101829078-0da2b700-3af8-11eb-809e-763d2f49810e.png)

**Comment by zdravkov** [comment]
Thank you for elaborating it!
We will do our best to fix it as soon as we can.

**Comment by zdravkov** [comment]
Hi @timritzer ,
It took us a while to handle this, sorry for this delay. In version 2.2.2 we added a separate type 'DropDownListVue3' that can be used in a vue 3 scenario with the idea in some of the next versions when we initiate a breaking change to make this type the default one.

Would you please let us know if this is working correctly for you when you have time to check it? Currently we have added just the DropDownListVue3 type and we will add the other ones in the next version.
Greetings,
Plamen

**Comment by zdravkov** [comment]
All the components are added Vue3 types in version 2.5.0
