### ISSUE TITLE
Remove computed properties from virtual scrolling demo

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#9]
## I'm submitting a...

* Bug report 

## Current behavior
Virtual scrolling is not smooth with 500000 items.

## Expected behavior
Virtual scrolling should be smooth with 500000 items.

**Comment by zdravkov** [comment]
It seems like the issue is caused by the usage of computed properties in the demo code. When we remove the and use functions it seems to work correctly.https://github.com/telerik/kendo-vue-private/pull/78

**Comment by mparvanov** [comment]
The following issue is observed in Edge only with the these changes:

1. Use the demo-fixes branch
1. Open the following demo from the sample application in Edge: 
http://localhost:3000/examples/DocsExamples/scrolling/virtual.html

The browser becomes unresponsive and the demo page is not loaded successfully.

**Comment by zdravkov** [comment]
The issue was caused by the fact that I have left 500000 items and the createRandomData method was failing in Edge . It started failing over 350000 - I set it back to 50000 for the demo.
