### ISSUE TITLE
Native AutoComplete: Data in the popup doesn't scroll to the highlighted item 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#92]
## I'm submitting a...
* Bug report 

## Current behavior
The record that matches the search criteria of the AutoComplete is highlighted in the popup but the data is not scrolled to this highlighted record. 

## Expected behavior
The data in the AutoComplete popup should be scrolled to the highlighted element 

## Minimal reproduction of the problem with instructions
1. Open [this Demo](https://www.telerik.com/kendo-vue-ui/components/dropdowns/autocomplete/#toc-basic-usage)
2. Write "Denmark"
3. If you scroll the popup data "Denmark" will be highlighted but this scrolling should be automatic.

**Comment by zdravkov** [comment]
Fixed in 2.1.1 - https://stackblitz.com/edit/bre9sq-p5mv2p?file=package.json
