### ISSUE TITLE
Filter operators of the Native Grid cannot be selected in there is no filter data entered

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#94]
## I'm submitting a...
* Bug report 
## Current behavior
The user cannot select a filter operator if the filter input doesn't have entered data.

## Expected behavior
The user should be able to pre-select a filter operator no matter if there is data entered in the filter input or not.

## Minimal reproduction of the problem with instructions

1. Open [this StackBlitz example](https://stackblitz.com/edit/mbyrwj-wcn6zp?file=src/main.vue)
2. In the Product Name column, I click the filter operator button
3. Select "Ends with"
4. Click the filter operator button again and see that "Ends with" is not selected.
5. Type "g" in the filter text field. Grid updates but doesn't filter the data by "Ends with" filter.
6. Click the filter operator button and see that "Contains" is selected instead of "Ends with"
7. Select "Ends with" once more and Grid filters correctly

**Comment by zdravkov** [comment]
fixed in 2.3.1 version
