### ISSUE TITLE
(Vue 3)The Native Input element configured with v-model directive is initialized with lazy modifier

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#98]
## I'm submitting a...
* Bug report

## Current behavior
The value of the Native Input is updating the model after the input is focused out. It behaves as the [lazy modifier](https://hohanga.medium.com/vue-3-v-model-modifiers-and-components-ae58e3b4e963) is applied to it. The reported behavior is replicable only in Vue 3. 

## Expected behavior
The value of the model the Input is bound to should be updated on every user input as can be observed in [this StackBlitz example](https://stackblitz.com/edit/m4lmdx-yazavy?file=index.html).

## Minimal reproduction of the problem with instructions
1. Open [this StackBlitz project](https://stackblitz.com/edit/k4bk2r-uansrp?file=src/main.vue)
2. Enter random symbols in the Input

The model is updated when you focus out the Input

**Comment by PekoPPT** [comment]
A similar issue is replicable in [this StackBlitz example](https://stackblitz.com/edit/6rzifg-kupjfi?file=src/main.vue). The input event of the Input component is not triggered in Vue 3 scenario. The same is working correctly in Vue 2 - https://stackblitz.com/edit/vsqzrs-5bdda1?file=index.html

The above is reported in ticket: 1513574

**Comment by zdravkov** [comment]
fixed in version 2.2.2
