### ISSUE TITLE
The popup lists of the Native Date inputs and the Dropdowns don't detect collision with browser's boundaries 

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-vue#99]
## I'm submitting a...
* Bug report 
## Current behavior
When the Date Inputs or DropDowns are positioned at the bottom of a page, their popup continues to open below the input field. This causes the popup to appear beyond the browser's boundaries, making the users unable to use the popup.  

## Expected behavior
The position of the popups of the Date inputs and DropDowns should be automatically changed based on the available space below each of the components. If there is not enough space to open the popup below the component's input, the popup should appear above the input. 

## Minimal reproduction of the problem with instructions
1. Open [this StackBliz example](https://stackblitz.com/edit/hft5nl-bw9xwa?file=src/main.vue)
2. Click on the "Open in a New Window" button at the right corner
3. In the opened browser window, scroll to the bottom of the page
4. Open the popup of the DropDownList

**Comment by PekoPPT** [comment]
Related to this FR: https://feedback.telerik.com/kendo-vue-ui/1507554-add-property-that-controls-the-position-of-the-popup-that-is-part-of-the-dropdownlist-component

**Comment by zdravkov** [comment]
Fixed in the 2.2.1 version - https://stackblitz.com/edit/hft5nl-32uogg?file=src/main.vue
